### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by manuelRestrep0** [MAKAIABootcamp/fundamentos-back1#1]
## Explicación del desarrollo técnico: 
Para realizar el ejercicio se utilizó lo aprendido en clase y se dividió la pagina en 3 partes: un header con el titulo, un main que contiene el nombre del pokemon, la imagen y una tabla con las caracteristicas; Luego un footer con imagenes de otros pokemones. 
## Imagen de la vista  
![image](https://user-images.githubusercontent.com/94997816/207486945-883dd8cb-0372-4f45-afcc-5fcecbd6b4d3.png)

## Estadísticas de Wakatime 
![image](https://user-images.githubusercontent.com/94997816/207486985-6738b7b2-df68-41d5-9c78-6acd6273b9c5.png)

## Integrantes
Juan Manuel Restrepo Galarcio @manuelRestrep0 
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 94%
Retroalimentación: En el algoritmo compraProducto hay un error de escritura en el llamado de la variable precio1 (se llama eprecio1) en la línea 4 para el cálculo del precio total de los producto. 

# Tarea Pokedex
Calificación: 85%
Retroalimentación: En el Index.html: Se observa uso de HTML Semántico. Sin embargo. Los estilos de la página solo utiliza el 50% del ancho de la pantalla.
