### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by salazar3148** [MAKAIABootcamp/fundamentos-back1#10]
## Preview [Despliegue](https://bryanpinzon.github.io/pokedexSprint1/)
![207508532-4cfef3e4-0e56-4044-8c72-ba967b5b0f93](https://user-images.githubusercontent.com/105958626/207768746-b98ca689-d153-49a7-a592-05ef243ead06.png)

## Christian David Salazar Marulanda @salazar3148 [Algoritmos](https://1drv.ms/u/s!Ahjj22hYf8zCb8XdzWphguc7Osg?e=c10xZc)
![207510975-24074939-a37a-4a19-b5f5-ffd828d33aea](https://user-images.githubusercontent.com/105958626/207768757-68f1474a-9b2e-44b2-859a-ee2bbca623a0.png)

## Brayan Enrique Pinzón Quiñonez @BryanPinzon [Algoritmos](https://drive.google.com/drive/folders/1z9gqGrtfFxZkzMtanOrv26HvYOhj_mRC)
![207511024-1ecdd99a-38df-4452-8b21-a99642360f15](https://user-images.githubusercontent.com/105958626/207768766-8ce90c18-52fe-42b8-97ee-b2f574e012f5.png)

![image](https://user-images.githubusercontent.com/105958626/207769593-b913e04c-f483-4ee2-b6fd-c301e7efaba4.png)

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
### Christian David Salazar Marulanda
Calificación: 100%
### Brayan Enrique Pinzón Quiñonez
Calificación: 100%
# Tarea Pokedex
Calificación: 98%
Retroalimentación: Muy buen uso de la estructura del HTML Semántico; sin embargo, se observa el contenido del footer desbordado del ancho de la pantalla.
