### ISSUE TITLE
Entrega workshop sprint 1

### ISSUE THREAD

**Issue by Strugtter** [MAKAIABootcamp/fundamentos-back1#11]
# URL del repositorio : [Pokedex](https://github.com/Strugtter/Makaia.git)
# Explicacion del desarrollo tecnico.
Partiendo del modelo de bloques realice la pagina de la siguiente forma:
Body componentes: Header, main y foooter.
Header: Tiene el titulo principal "Pokedex" y la imagen de una poquebola.
Main: Tiene una section y un aside.
Main-section: Contiene un header para el nombre y una imagen de la habilidad del pokemón. Además, de la imagen a color del pokemon.
Main-Aside: Contiene una table que indica las caracteristicas espesificas del pokemón.
Footer: Contiene una seccion y un Titulo h1.
Footer-section: Contine un elemento Nav & hipertexto, donde agrege las imagenes de los posibles pokemon a revisar.
Nota: La navegacion tiene cambio de color y puntero cuando el mouse pasa por encima de una de los OTHERS pokemón.
#Imagenes de la vista
![PaginaWeb](https://user-images.githubusercontent.com/106613231/207774201-ba899aac-a616-4d45-8b25-6e3759372732.JPG)
![ClicMouse](https://user-images.githubusercontent.com/106613231/207774209-149934f7-53a3-4932-9096-6c44eba41af9.jpg)
# WakaTime
![WakaTime](https://user-images.githubusercontent.com/106613231/207774244-9a10e8e6-1449-46ed-b312-125c48c8ec3b.JPG)
#Integrantes
Camilo Andres Botina Trujillo
Usuario: Strugtter
@WhitneySt

**Comment by WhitneySt** [comment]
Calificación: 87%
Retroalimentación: Faltó proporcionar URL de la página.
