### ISSUE TITLE
Entrega workshop 1 Sprint

### ISSUE THREAD

**Issue by dianaperezdv** [MAKAIABootcamp/fundamentos-back1#13]
## **Desarrollo técnico** 
Con la intención de realizar una página similar a la plantilla presentada de una pokedex se realizó un archivo html. 
Se dividió en un header, para el título de la página; en el body se crearon dos secciones, una para mostrar el pokemon y otra para la información; y finalmente en el footer la opción de ver otros pokemon. 
En CSS se realizó la organización y diseño de los datos, se aplicó un hoover a las imágenes de los pokemon del footer. 

## 
![image](https://user-images.githubusercontent.com/47093819/207787058-4149b78f-d468-455d-9fd2-7925d41a3ddc.png)

## Entrega ejercicios de Pseint [Pseint.zip](https://github.com/MAKAIABootcamp/fundamentos-back1/files/10234085/Pseint.zip)

Integrantes: Diana Pérez
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 100%
# Tarea Página Pokedex
Calificación: 87%
Retroalimentación: Faltó proporcionar URL del despliegue de la página en la issues.
