### ISSUE TITLE
Entrega workshop 1 sprint #1

### ISSUE THREAD

**Issue by VivianaGuzmanBuritica** [MAKAIABootcamp/fundamentos-back1#14]
## Explicación del desarrollo técnico
Se realizo un maquetado de una Pokedex,, haciendo uso de HTML  usando  etiquetas semanticas. Por su parte en el CSS se implementa el uso de fuentes, flex, y hover en el footer, tambien se puede apreciar en modo movile 
## Imagen de las vistas
![image](https://user-images.githubusercontent.com/82985780/207361268-01138be2-0060-485e-bfb2-b8c3be02a10e.png)
![image](https://user-images.githubusercontent.com/82985780/207361635-0feb391b-7abf-4322-8a17-e5336d742f8e.png)
![image](https://user-images.githubusercontent.com/82985780/207362851-8b1bf775-e733-4063-8716-701e07d9b6f0.png)
## Estadísticas de Wakatime [Wakatime](https://wakatime.com/dashboard?start=2022-12-07&end=2022-12-13)
![image](https://user-images.githubusercontent.com/82985780/207369904-ae99dcd5-3066-487d-8907-84d8b2b2c7f0.png)
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
### Jesús Jimenez Rosario: 
Calificación: 100%
### Viviana Guzmán: 
Calificación: 95%
Retroalimentación: En el algoritmo de calcular el total a pagar de 5 producto, faltó la lectura de los precios de cada producto y el cálculo de subtotal.
# Tarea Pokedex
Calificación: 96%
Retroalimentación: La URL de despliegue proporcionada no se encuentra disponible en el momento de revisar y cerrar el issues.
