### ISSUE TITLE
Pseudocodigo

### ISSUE THREAD

**Issue by Edward-Reyes-Vanegas** [MAKAIABootcamp/fundamentos-back1#15]
## Explicación del desarrollo técnico
El objetivo es aprender lógica de programación, declaración de variables e introducción con el entorno de programacion
## URL del repositorio
@Edward-Reyes-Vanegas 
## Imagen de las vistas
@WhitneySt

**Comment by WhitneySt** [comment]
Calificación: 100%, Excelente trabajo!
