### ISSUE TITLE
Entrega workshop 1 sprint #1

### ISSUE THREAD

**Issue by Edward-Reyes-Vanegas** [MAKAIABootcamp/fundamentos-back1#16]
## Explicación del desarrollo técnico
Esta pagina tiene como objetivo aprender conceptos y usos de codigo html y estilos ccs
## URL del repositorio
@Edward-Reyes-Vanegas 
@rmazov Ricardo Mazo 
## Imagen de las vistas
@WhitneySt
![wakatime1](https://user-images.githubusercontent.com/120218145/207872290-566a8030-a3d0-4460-a20c-03a5474675c2.jpg)
![wakatime2](https://user-images.githubusercontent.com/120218145/207872328-3fcd4491-d9e8-47c8-8c79-3050319e8a10.jpg)
![wakatime3](https://user-images.githubusercontent.com/120218145/207872353-a1d24fcc-ce95-4b08-ab77-b40644798875.jpg)

**Comment by WhitneySt** [comment]
## Calificación
100%

### [Repositorio del Pokedex revisado](https://github.com/Edward-Reyes-Vanegas/makaia)
