### ISSUE TITLE
## https://rmazov.github.io/makaia/

### ISSUE THREAD

**Issue by Rmazov** [MAKAIABootcamp/fundamentos-back1#17]
## [URL de despliegue](https://rmazov.github.io/makaia/)
![wakatime](https://user-images.githubusercontent.com/97861713/207751962-bfe22e5f-d973-4036-9b76-9963eb8071a1.png)
## entrega Ricardo Mazo @Rmazov  @Edward-Reyes-Vanegas
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt @Rmazov 
Calificación: 100%

# Tarea Página Pokedex
Calificación: 100%
