### ISSUE TITLE
Entrega workshop 1 sprint #1

### ISSUE THREAD

**Issue by Pipe1098** [MAKAIABootcamp/fundamentos-back1#18]
## Explicación del desarrollo técnico: 
Se desarrollo una pagina web básica, para practicar los conceptos vistos en clase sobre html y css como header, footer, body, agregar imágenes y modificar estilos.
## Url de la pagina  https://pipe1098.github.io/Sprint-1/
Wakatime
![Wakatime](https://user-images.githubusercontent.com/90018701/207971748-1aa37d57-801d-4e5d-a9b6-ccedeaebaab1.png)

**Comment by WhitneySt** [comment]
### Calificación
92%
### Retroalimentación
La página no cubre el 100% del ancho de la pantalla, las imágenes empleadas tienen fondo.
