### ISSUE TITLE
Entregable proyecto final Sprint 1

### ISSUE THREAD

**Issue by VivianaGuzmanBuritica** [MAKAIABootcamp/fundamentos-back1#19]
## Descripción de la entrega 
Desarrollo de una aplicación en JavaScript la cual simula el funcionamiento de un cajero automático, en donde se podrán realizar las siguientes tareas:
- Registrar Administradores y Clientes.
- Ingresar y realizar actividades diferenciadas por tipo de usuario que son depositar o retirar dinero.
-  Mostrar en pantalla el saldo por denominación de billetes cargados previo y posterior a las transacciones.
- Funcionamiento cíclico hasta que se decida dejar de usar el Cajero Automático.

## URL[Wakatime](https://wakatime.com/dashboard)
![image](https://user-images.githubusercontent.com/82985780/208005613-0f385a26-be1f-4bc7-9976-b6a537785f31.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo!
