### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by sofmillan** [MAKAIABootcamp/fundamentos-back1#2]
## URL del repositorio:[Pokedex](https://github.com/sofmillan/pokedex)
Esta actividad corresponde al primer workshop del sprint, una página web sencilla con el contenido de una pokedex, cuya estructura se divide principalmente en un header, donde se encuentra el logo y título, el main, donde se aprecia la información de un pokemon en específico y finalmente el footer, donde el usuario tendría la capacidad de desplegar los datos de otros pokemon.
 
**Github pages:**[Pokedex page](https://sofmillan.github.io/pokedex/)

**Imagen de la vista**
![preview](https://user-images.githubusercontent.com/98916125/207498311-6af3e79a-bc15-4042-9f93-baedd6d3a8a7.png)

<img width="213" alt="image" src="https://user-images.githubusercontent.com/98916125/207498464-eb62680b-49c6-4e88-aa3b-9656b111d60c.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/98916125/207498508-931bbded-294e-469d-ada1-e2d0fcf56ce1.png">

**Wakatime**
<img width="814" alt="image" src="https://user-images.githubusercontent.com/98916125/207498662-e63933c0-9028-41d2-b479-526c37102870.png">

**Ejercicios PSeInt:** https://github.com/sofmillan/PracticaPseint
**Hecho por:** Sofía Millán   usuario:sofmillan
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmos PSEInt
Calificación: 100%
Retroalimentación: Felicitaciones, excelente trabajo!
# Tarea Página Pokedex
Calificación: 100%
Retroalimentación: Felicitaciones, excelente trabajo!
