### ISSUE TITLE
Entrega workshop 1 sprint #1

### ISSUE THREAD

**Issue by ghost** [MAKAIABootcamp/fundamentos-back1#20]
# URL: [Repositorio](https://github.com/camilorestrepodev/Entrega-workshop-1-sprint-1)

# URL DE DESPLIEGUE: [URL DE DESPLIEGUE](https://camilorestrepodev.github.io/Entrega-workshop-1-sprint-1/)

# Explicación del desarrollo técnico:
Se desarrollo un proyecto web basándose en la temática de Pokémon (pokedex) en este se involucraron:

- Diseños de HTML5 (Encabezados, párrafos, atributos y formatos)
- Diseños de Css (Margenes, padding, elementos de bloque y de lineal, navegación responsive, flexbox)

# Imágenes del proyecto:
(Adaptabilidad para diferentes tamaños)
![pokedex](https://user-images.githubusercontent.com/119947851/208014163-09c6ff68-da0c-4654-b0bb-b2a463a466d0.png)

> 

![Cel](https://user-images.githubusercontent.com/119947851/208014376-c4c06fb6-3fe2-4e09-929c-96e8e65b5717.png)
![cel part 2](https://user-images.githubusercontent.com/119947851/208014368-7ec462d0-7ec3-40a7-9fde-32c2bfb762a0.png)

# Ejercicios en clase de seudocódigo con el programa Pseint:
[Ejercicios pseint.zip](https://github.com/MAKAIABootcamp/fundamentos-back1/files/10242394/Ejercicios.pseint.zip)

# Estadísticas de WAKATIME sobre el proyecto de web-pokedex:
![wakatimepokedex](https://user-images.githubusercontent.com/119947851/208809638-a4909196-9327-48ce-b048-cc7d1a8c3715.png)

# Presentado por:
Juan Camilo Restrepo B.

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 100%
# Tarea Página Pokedex
Calificación: 87%
Retroalimentación: Faltó proporcionar URL de despliegue en el issues.
