### ISSUE TITLE
Sprint 1 (Cajero Automático)

### ISSUE THREAD

**Issue by imsntiago** [MAKAIABootcamp/fundamentos-back1#22]
## URL del repositorio de la actividad.
https://github.com/yoyisdev/sprint-1
## URL del despliegue del aplicativo
https://yoyisdev.github.io/sprint-1/
## Descripción del desarrollo de la actividad
Algoritmo que trata de simular la función de un cajero. Para su realización se implemento el uso de ciclos, condicionales, operaciones matemáticas básicas, al igual que el uso de contadores y variables bandera para validación de información ingresada por el usuario.
## Imagen del aplicativo
![image](https://user-images.githubusercontent.com/120517759/208754729-0adf03aa-59f1-4516-99c2-266205a0919f.png)
## Estadísticas generadas en el dashboard de Wakatime
![image](https://user-images.githubusercontent.com/120517759/208755337-bee3b30a-1144-40a7-ae85-f152955d3664.png)
## Participante
Santiago Jaramillo
## Profesora
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
90%
### Retroalimentación
El aplicativo no permite el retiro de dinero por parte de un usuario tipo cliente priorizando la denominación de los billetes.
