### ISSUE TITLE
Proyecto sprint 1

### ISSUE THREAD

**Issue by manuelRestrep0** [MAKAIABootcamp/fundamentos-back1#23]
## Imagen del aplicativo: 
![image](https://user-images.githubusercontent.com/94997816/208935718-23bcd345-f941-4452-b008-e38db1d38f7b.png)
## Wakatime: 
![image](https://user-images.githubusercontent.com/94997816/208935878-b4a2be45-5a4d-4af0-bf61-77418ce46523.png)

Por: @manuelRestrep0
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
98%
### Retroalimentación
El array fue construido con objetos en formato JSON.
