### ISSUE TITLE
Proyecto sprint 1 Cajero

### ISSUE THREAD

**Issue by sofmillan** [MAKAIABootcamp/fundamentos-back1#24]
##Url del repositorio: [Repositorio](https://github.com/sofmillan/CajeroJS) 
##Url del github pages:  [Pages](https://sofmillan.github.io/CajeroJS)
##Descripción:
Este proyecto es una simulación de un cajero, en el cual, dependiendo del  tipo de usuario, uno o dos, podrá introducir o retirar dinero del cajero respectivamente, además después de cada operación mostrará el dinero restante por cada denominación.
##Wakatime
<img width="797" alt="image" src="https://user-images.githubusercontent.com/98916125/208953485-8c29d146-67cb-4616-99bc-11debfa1c94a.png">
##Imagen del aplicativo
<img width="380" alt="image" src="https://user-images.githubusercontent.com/98916125/208954211-5a7dc60f-ab46-4f61-8f39-a8ff93124d43.png">

Hecho por: Sofía Millán
Usuario: sofmillan
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Felicitaciones
