### ISSUE TITLE
Entrega Proyecto Sprint 1

### ISSUE THREAD

**Issue by afprietoa** [MAKAIABootcamp/fundamentos-back1#25]
## Desarrollo técnico:

Se construyo la lógica de un cajero automático para simular las transacciones usando POO y arreglos en JavaScript, para visualizar las operaciones se construyo una interfaz de usuario con CSS y HTML.  La aplicacion permite la autenticación del usuario con las credenciales designadas dandole permisos para depositar el dinero por tipo de denominación. Así mismo, el usuario puede hacer retiros y visualizar la cantidad de billetes requeridos para completar dicha operación.

#### Login Screen
![image](https://user-images.githubusercontent.com/68924563/208971587-20629cd0-a020-4cf8-810d-c9b74c43a484.png)

#### Deposit Screen
![image](https://user-images.githubusercontent.com/68924563/208972298-52b0fd3c-7ac5-434a-a131-9634db55b1a4.png)

#### Withdrawal Screen
![image](https://user-images.githubusercontent.com/68924563/208972510-df41d620-810d-4f48-9fd0-e67886491207.png)

#### Results Screen
![image](https://user-images.githubusercontent.com/68924563/209346201-cb9688c2-e1dc-4a62-9209-0c3d38aa6c61.png)

### Wakatime

![image](https://user-images.githubusercontent.com/68924563/208971450-9e6e8254-ade4-44cd-8fea-b502d7170459.png)

## Integrante:
     - Andrés Felipe Prieto Alarcón

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
61%
### Retroalimentación

1. La URL de despliegue suministrada no se encuentra disponible
2. El array de los datos fue construido con formato tipo JSON
3. No se valida las acciones de retiro y depósito por tipo de usuario
4. No se realiza la validación de disponibilidad de dinero en cajero
5. No se construyó la acción de retiro de dinero.
