### ISSUE TITLE
Entrega Sprint 1  Cajero 

### ISSUE THREAD

**Issue by Jaime-U-Lopez** [MAKAIABootcamp/fundamentos-back1#26]
# Proyecto Sprint 1 : Cajero Automático

## URL GitHub Repository: https://github.com/Jaime-U-Lopez/Bootcamp_Macaia/tree/main/sprint1

Desarrollo técnico:
Se realizó imitando la operación de un  de un cajero automático para simular las transacciones usando funciones  y arreglos en JavaScript, la cual se visualiza con Alert y Console.  
en la cual solicita autenticación, ingresos de Billetes si es Administrador o si es Cliente la opción de retirar dinero y al final muestra el saldo 

### WebSite : 
![image](https://user-images.githubusercontent.com/50783391/209039138-ea53a4f0-80ed-405e-b45f-917d985b7899.png)

### Wakatime:
![image](https://user-images.githubusercontent.com/50783391/209038156-68b669e2-cd84-48ca-a967-3c1a5172e395.png)

![image](https://user-images.githubusercontent.com/50783391/209038252-da2b7d08-10da-4771-9676-c16ea21a031d.png)

Integrante:
 - Jaime Orlando Urrego 
@Jaime-U-Lopez
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
93%
### Retoalimentación

1. El aplicativo presenta error en la actualización de la cantidad de billetes en el array de billetes depositados en la acción de depósito por parte de un usuario tipo admin
2. El aplicativo presenta error en la presentación de cuánto dinero puede suministrar a un usuario tipo cliente en consola
