### ISSUE TITLE
Entrega proyecto 1 sprint

### ISSUE THREAD

**Issue by EmmanuelUs4** [MAKAIABootcamp/fundamentos-back1#27]
## URL del repositorio
Observación: a pesar de haber hecho el cambio antes de subir el repositorio, el código queda con un gran espacio de líneas vacías en la mitad.

https://github.com/EmmanuelUs4/Cajero.git
##  URL Git pages
((No me acuerdo cómo  se hace esto, pero estoy en ello))
## Explicación del desarrollo técnico

Desarrollo de un cajero en linea, que permite a una cuenta de Administrador, cargar dinero; y a una cuenta de Cliente, retirar dinero.

Internamente el cajero ha de guardar los cambios que se realizan en el dinero que posee, ya sean por cargas de Administrador o retiros de Clientes, además de mostrar esos cambios en consola

## Imagen de Wakatime
![Sin título](https://user-images.githubusercontent.com/120135105/209050246-2a64a83c-b5c6-4ceb-af11-876cfaa62ce2.png)

![Sin título3](https://user-images.githubusercontent.com/120135105/209056778-700842e1-3044-47cd-8ee6-91fa4bc6442a.png)

![4](https://user-images.githubusercontent.com/120135105/209056780-7e930af5-8ef1-40bb-b2a2-ca205557983f.png)

## Imagen de vistas
![Sin título2](https://user-images.githubusercontent.com/120135105/209050533-bfcdbc11-e9fd-4bcd-8797-e4da93f89729.png)
 
Emmanuel Usme - EmmanuelUs4
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
85%
### Retroalimentación

1. No se construye el array de usuarios
2. No se declaran apropiadamente algunas variables como : 
![image](https://user-images.githubusercontent.com/98284374/212775985-165601cb-d05d-4d98-9f34-1180e1fa0519.png)
3. La función de retiro funciona parcialmente para realizar las validación en la priorización de los billetes de mayor denominación.
