### ISSUE TITLE
Entrega Proyecto sprint 1

### ISSUE THREAD

**Issue by Strugtter** [MAKAIABootcamp/fundamentos-back1#28]
# URL del repositorio: [CajeroAutomatico](https://github.com/Strugtter/Sprint-1.git)
# Desarrollo técnico: Se realizó la simulacion de un cajero Automatico, empleado localstorage para el almanamiento de la informacion, ademas se crearon tres interfaces que son de inicio de sesión, cliente y administrador. El cliente puede unicamente realizar retiros y el administrador puede ejecutar la carga de dinero en billetes de 5,10,20,50 y 100 mil pesos.  
# Imagenes de vista:
![IniciosSesion](https://user-images.githubusercontent.com/106613231/209055132-999bc136-16ed-4d4c-bf71-00c8dc910656.JPG)
![PantallaAdmin](https://user-images.githubusercontent.com/106613231/209055135-5beb0cb6-a70f-4152-a207-28f170d68ba5.JPG)
![PantallaCliente](https://user-images.githubusercontent.com/106613231/209055139-7adbf447-6302-4d90-a144-a3e4b06dda68.JPG)
# WakaTime:
![WakaTime](https://user-images.githubusercontent.com/106613231/209055391-6586924c-1a85-4d74-9719-53d81e2ffb1a.JPG)
#Integrante: Camilo Andres Botina Trujillo
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo, sin embargo no se suministra en el issues la URL de despliegue
