### ISSUE TITLE
Proyecto Sprint 1

### ISSUE THREAD

**Issue by BrianStevenV** [MAKAIABootcamp/fundamentos-back1#29]
[URL REPOSITORIO] https://github.com/BrianStevenV/Entrega-Sprint-1
[URL DESPLIEGUE] https://brianstevenv.github.io/Entrega-Sprint-1/
La actividad consiste en generar el servicio de un cajero automatico, tanto servicio de administrador como servicio de cliente, el servicio de administrador consiste en permitir llenar manualmente el cajero, y el servicio de cliente consiste en retirar el dinero de cajero.
![wakatimesprint1](https://user-images.githubusercontent.com/119947948/209060208-2fd6f6c5-b194-40ac-bc47-9288f4c62c70.png)
[FOTO APLICATIVO]
![fotocajero](https://user-images.githubusercontent.com/119947948/209060758-5e47d0b8-31ec-417f-9cf5-46b9a705126e.png)

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
81%
### Retroalimentación

1.  Se repiten líneas de código que pudieron ser simplificadas con el uso de estructuras cíclicas o métodos de arrays
2. El código presenta inconveniente con la actualización del array de billetes depositados y validación para suministrar los billetes priorizando los de mayor denominación en la acción de retiro.
