### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by BrianStevenV** [MAKAIABootcamp/fundamentos-back1#3]
##https://brianstevenv.github.io/trabajo_pokedex/
#https://github.com/BrianStevenV/trabajo_pokedex#Repositorio
##Este es un proyecto HTML y CSS, el proyecto se realizo con un header sencillo, donde con sus respectivas clases sirvio para realizar todos los estilos, el main y footer, esta hecho a base de divs que generan espacios y se utilizaron para tratar de forma personalizada el espacio de cada elemento que hay en dichas etiquetas de HTML.
##Imagen de la Vista
Header
![FotoHeader](https://user-images.githubusercontent.com/119947948/207717349-ebb66072-010f-496b-b771-c30915ce2efd.png)
Foto Footer con Hoover en Otros
![fotoHooverFooter1](https://user-images.githubusercontent.com/119947948/207717492-0321d534-052a-43e2-895e-e455cef56e71.png)
Foto Footer con Hoover en Pokemones inicio.
![fotoHooverFooter2](https://user-images.githubusercontent.com/119947948/207717718-2aa8696e-b017-4aac-9bff-8da5f8b06346.png)
Foto Footer con Hoover en Pokemones final.
![fotoHooverFooter3](https://user-images.githubusercontent.com/119947948/207717787-6c71ca70-d32f-409c-b8eb-ec942d5a8912.png)
WakaTime
![FotoWakaTime](https://user-images.githubusercontent.com/119947948/207717858-180afa1b-3388-4224-985a-1f2ede01709e.png)
**Ejercicios PSeInt: https://github.com/BrianStevenV/pseint
##Hecho por: Brian Steven Acevedo Villegas y Emmanuel Usme "Cada uno subio su propio trabajo, mostrando su respectivo conocimiento y esfuerzo ".
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 99%
Retroalimentación: En el algoritmo productos, se calcula el iva de los productos con diferentes porcentajes.

# Tarea Página Pokedex
Calificación: 94%
Retroalimentación: Muy buen manejo de la estructura HTML Semántico; sin embargo, en el despliegue, la página no reconoce la imagen del logo y se desbordan los textos (como títulos y descripciones en la tabla) de sus elementos contenedores.
