### ISSUE TITLE
Proyecto Sprint 1

### ISSUE THREAD

**Issue by EnriquePinzon** [MAKAIABootcamp/fundamentos-back1#31]
1. URL del repositorio (https://github.com/BryanPinzon/Entrega-proyecto-sprint-1)
2. URL despliegue (https://bryanpinzon.github.io/Entrega-proyecto-sprint-1/)
3. Descripción del aplicativo:
El aplicativo simula un cajero Automatico, donde permite validar el documento del usuario y contraseña, tipo de usuario en caso de ser Administrador o Cliente, permite cargar interfaz como administrador para ingresar dinero y retirar como cliente en base a lo que hay disponible. Muestra cantidad de billetes por cada denominación y la suma total.
![imagen](https://user-images.githubusercontent.com/114439510/209060433-bb7ac7f3-2894-4b95-9595-434f726dd18b.png)

Dashboard Wakatime
![imagen](https://user-images.githubusercontent.com/114439510/209061274-3356a345-82b9-481f-a725-81462432430e.png)
![imagen](https://user-images.githubusercontent.com/114439510/209060673-f9c9b8c0-321c-4183-969b-361f12130972.png)
![imagen](https://user-images.githubusercontent.com/114439510/209061324-01b2678c-ae72-4a84-8659-eee07dd1d426.png)

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
93%
### Retroalimentación

1. Implementa función de registro. 
2. El cajero no prioriza la cantidad de billetes a entregar, el cliente puede seleccionar la cantidad de billetes por denominación que quiere recibir.
3. En el despliegue de la página no permite el ingreso de  sus datos
![image](https://user-images.githubusercontent.com/98284374/212779296-954dcc49-971e-40bc-9269-9c70d55bf2c0.png)
