### ISSUE TITLE
Sprint 1 Proyecto Cajero

### ISSUE THREAD

**Issue by Edward-Reyes-Vanegas** [MAKAIABootcamp/fundamentos-back1#32]
![wakatime1](https://user-images.githubusercontent.com/120218145/209393169-a2e7ebc2-1871-4d1d-82d7-177ce783902e.jpg)
![wakatime3](https://user-images.githubusercontent.com/120218145/209393171-81d1921b-9ed2-46c3-9297-ef65b7518131.jpg)
## Explicación del desarrollo técnico
Esta es una aplicacion creada para aprender estructuras de de comparacion, bucles 
## URL del repositorio
@Edward-Reyes-Vanegas 
## Imagen de las vistas
@WhitneySt

**Comment by Edward-Reyes-Vanegas** [comment]
![CAJERO1](https://user-images.githubusercontent.com/120218145/209392726-e2ab36d7-b62f-43e7-96d7-0a89d854e854.png)
![CAJERO2](https://user-images.githubusercontent.com/120218145/209392729-8706aba7-3b3d-4963-9659-0d07a3e6bc9f.jpg)

**Comment by WhitneySt** [comment]
### Calificación
61%
### Retroalimentación

1. No suministra la URL de despliegue de la página
2.  El código presenta inconvenientes en mostrar los billetes depositados en consola.
3. No cuenta con el bucle de ingreso de los datos de usuario y la acción de retiro de dinero por parte de un usuario cliente.
