### ISSUE TITLE
entrega:[cajero automatico, pagina pokedex, problemas ejercicios]

### ISSUE THREAD

**Issue by yorlancano** [MAKAIABootcamp/fundamentos-back1#33]
# URL del repositorio : [cajero automatico](https://github.com/yorlancano/cajero-automatico/tree/gh-pages)
# URL despliegue:  [pagina cajero](https://yorlancano.github.io/cajero-automatico/)
# Explicación del proyecto:

-En la creación de este cajero automático dispusimos un archivo js (JavaScript) y un archivo índex (HTML) en donde utilizamos bucles for y while ,
haciendo uso igualmente de  listas y objetos para la solución de nuestro problema. Que era lo que realmente teníamos que hacer, era que nuestro administrador ingresara el dinero al cajero y que hubiera un cliente que retiraría el dinero del cajero.

# IMAGEN:
![image](https://user-images.githubusercontent.com/111914633/209057440-f7dc848c-5ce3-4b50-b4aa-a30f4492fc41.png)

# WAKA-TIME:

![Captura de pantalla (1)](https://user-images.githubusercontent.com/111914633/209060063-bb194d8b-aa88-4950-9b9d-32ddc2496c37.png)
 
# 2 CAPTURA:

![Captura de pantalla (2)](https://user-images.githubusercontent.com/111914633/209060266-1039bc84-1f4f-4f23-ae4b-ebe47afcfa3a.png)

# URL del repositorio : [pagina pokedex](https://github.com/yorlancano/pagina-pokedex/tree/gh-pages)
# URL despliegue : [pagina pokedek](https://yorlancano.github.io/pagina-pokedex/)
Explicación del proyecto: 
- se creo una pagina web en donde utilizamos un archivo índex(HTML) con estilos(CSS) para la visualización de esta misma en donde se proyecta la información de uno de los pokemones y también se encuentran una visualización de cartas de los demás pokemones.

# IMAGENES:

![image](https://user-images.githubusercontent.com/111914633/209058340-4e67c772-c710-4248-9670-5843077ffc3b.png)

# SEGUNDA IMAGEN:

![image](https://user-images.githubusercontent.com/111914633/209058623-262e70d2-2acf-4415-8c3c-5b9c2b3e2dc6.png)

# WAKA-TIME:
![Captura de pantalla (3)](https://user-images.githubusercontent.com/111914633/209060630-8cec77b8-688f-4ea6-864d-0fb91c752491.png)

# 2 IMAGEN:
![Captura de pantalla (4)](https://user-images.githubusercontent.com/111914633/209060707-6675013b-32da-4b2e-859c-a07eeb4442d3.png)

# URL del repositorio: [problemas ejercicios](https://github.com/yorlancano/ejercicios-algoritmicos)

Explicación de los ejercicios:
Los ejercicios que realizamos nos ayudan a ver como se comporta un algoritmo a la hora de dar solución a un problema
y podemos ver que hay muchas maneras de darle solución.

nota: por fallos técnicos los ejercicios fueron realizados en java con el ide (intelling) 

# INTEGRANTES: 
yorlan yuhan marroquin cano
# ENTREGA A:
Whitney Stevenson

**Comment by WhitneySt** [comment]
# Tarea Algoritmo
Calificación: 97%
Retroalimentación: 

1. Se desarrolló los algoritmos con Java, en lugar de implementar la herramienta PSEInt o el lenguaje de Programación JavaScript
2. Se entrega la actividad por fuera del tiempo pactado

# Tarea Página Pokedex
Calificación: 98%
Retroalimentación: Se entrega la actividad por fuera del tiempo pactado

# Proyecto Sprint 1
Calificación: 64%
Retroalimentación: 

1. La funcionalidad de retiro de dinero no cumple con los requisitos del proyecto
