### ISSUE TITLE
cajero Ricardo mazo

### ISSUE THREAD

**Issue by Rmazov** [MAKAIABootcamp/fundamentos-back1#34]
## https://github.com/Rmazov/SPRINT1
![caje](https://user-images.githubusercontent.com/97861713/209062961-9e0f4d76-0390-4e7d-8247-380d4d805378.png)

**Comment by WhitneySt** [comment]
###  Calificación
95%
### Retroalimentación: 
Si la cantidad que se desea retirar no es múltiplo de 5 no realiza la transacción. Puede reducir líneas de código implementando bucles y métodos de arrays.
