### ISSUE TITLE
Cajero entrega Sprint 1 

### ISSUE THREAD

**Issue by sebastian1695** [MAKAIABootcamp/fundamentos-back1#35]

**Comment by sebastian1695** [comment]
# Cajero proyecto Sprint 1 
## URL https://github.com/sebastian1695/Cajero-
### Descripción: El proceso de creación del cajero se hizo mediante JS y lo que se busca es que el programa identifique el tipo de usuario entre administradores y clientes. Del mismo modo, el programa permite insertar dinero o retirar dinero. 

## Wakatime: 

![Screen Shot 2022-12-22 at 6 51 40 AM](https://user-images.githubusercontent.com/119948037/209129086-b76982b7-093b-4732-b0cd-f30835032df0.png)
![Screen Shot 2022-12-22 at 6 56 02 AM](https://user-images.githubusercontent.com/119948037/209129380-ca5a999e-6753-4c9d-8e93-9316189db2b9.png)

Integrante: Carlos Sebastián Rodríguez C


@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
63%
### Retroalimentación

1. Se debe reforzar los conceptos de funciones, contexto de las diferentes declaraciones (cíclicas, condiciones, funciones, etc.)
2. No se construyó la función de retiro de dinero
