### ISSUE TITLE
Entrega Sprint 1

### ISSUE THREAD

**Issue by dianaperezdv** [MAKAIABootcamp/fundamentos-back1#36]
[**Url del repositorio**](https://github.com/dianaperezdv/CajeroAutomatico)

**Descripción:** 
Se realizó en Javascript un programa que permitiera al usuario iniciar sesión y realizara acciones diferentes según el tipo de usuario. 

Wakatime:
Es más de una imagen porque moví el archivo por varias carpetas. 

![image](https://user-images.githubusercontent.com/47093819/209138694-d93ecacf-6fb1-404b-917d-3041d445da2c.png)

![image](https://user-images.githubusercontent.com/47093819/209138757-f697ebbe-6902-4cd1-a4cf-1ec8bd046f52.png)

Integrantes: Diana Camila Pérez del Valle

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
En el issues no se suministró la URL de despliegue.
