### ISSUE TITLE
Entrega Proyecto Sprint 1

### ISSUE THREAD

**Issue by ghost** [MAKAIABootcamp/fundamentos-back1#37]
# Proyecto Sprint 1:
## [URL REPOSITORIO](https://github.com/camilorestrepodev/Entrega-Proyecto-Sprint-1)

# Desarrollo Técnico:
Se desarrollo un simulador de cajero automático cumpliendo los requerimientos técnicos.
Que se profundizó en este simulador?
- Array de objetos
- Crear ciclos y bucles
- Crear funciones
- Crear clases

# Imagen de la vista:
![wakatimevista](https://user-images.githubusercontent.com/119947851/209153108-b411cb95-a722-4a5c-8bcc-defbc358bbc6.png)

# Wakatime Cajero Automático:
![wakatimecajeroautomatico](https://user-images.githubusercontent.com/119947851/209151879-735bcb17-e770-40d0-a3d2-3ffbdc158d9b.png)

Presentado Por:
Juan Camilo Restrepo B.

**Comment by WhitneySt** [comment]
### Calificación
96%
### Retroalimentación
La función retirar dinero presenta inconvenientes en las validaciones para solicitar retiro de dinero y mostrar en consola cuánto dinero puede entregar el cajero.
