### ISSUE TITLE
Entrega Proyecto Sprint 1 

### ISSUE THREAD

**Issue by Jesus482** [MAKAIABootcamp/fundamentos-back1#38]
# Proyecto Cajero Automatico

##  URL de la actividad : https://drive.google.com/drive/u/0/folders/1SZAnArLQwTawdbHiBkSn5k-xfIBULvD1?hl=es 

Detalle : no pude completarlo pero espero poder mejorar mis habilidades para proyectos futuros

Wakatime:
![Captura de pantalla (300)](https://user-images.githubusercontent.com/120477929/209269276-ed951ce5-6b83-49cd-91f9-4161d1e510d1.png)
![Captura de pantalla (301)](https://user-images.githubusercontent.com/120477929/209269277-fe3dd6db-8f0a-4cf3-b63e-88440df235aa.png)
![Captura de pantalla (302)](https://user-images.githubusercontent.com/120477929/209269278-e037683b-729a-49bb-9a99-69e4c2a5e442.png)
![Captura de pantalla (299)](https://user-images.githubusercontent.com/120477929/209269279-1a79ef5d-21cd-4033-b3be-c4f9f087dbb7.png)

Participantes: Jesus Jimenez

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
49%
### Retroalimentación

1. En el issues no se suministró la URL de despliegue ni la URL del repositorio del código del proyecto
2. Se califica con base al código presentado en la sustentación.
3. El código parcialmente ejecuta, las validaciones para iniciar sesión de un usuario por tipo de usuario, la función de depósito de billetes y las validaciones para las acciones que realiza un usuario admin y un cliente.
4. No se desarrolló el código para realizar la operación de retiro de dinero
