### ISSUE TITLE
Proyecto Sprint 1 

### ISSUE THREAD

**Issue by Pipe1098** [MAKAIABootcamp/fundamentos-back1#39]
## Descripción:
Proyecto que simula el funcionamiento de un cajero de forma básica, se implementaron, objetos, arreglos, bucles y condicionales para el desarrollo y se muestran todos los datos por consola.

![image](https://user-images.githubusercontent.com/90018701/209271415-49fac607-4903-4a15-9827-5ca2798fe594.png)

Por: Luis Felipe Penagos Bedoya

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo, código muy organizado; sin embargo, el issues no proporciona la URL de despliegue de la actividad.
