### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by afprietoa** [MAKAIABootcamp/fundamentos-back1#4]
## Desarrollo técnico:

Se construyo una interfaz responsive de un Pokédex aplicando HTML semántico, CSS responsive y JavaScript API REST. La implementación consta de una pantalla dinámica, la imagen y la información del pokemón cambia con la selección de este en en carrousel.

#### Desktop & Tablet
![image](https://user-images.githubusercontent.com/68924563/207717174-2b6c1277-c224-43a1-a954-31742e4fc16a.png)
![image](https://user-images.githubusercontent.com/68924563/207717093-f0b3d830-47fe-4e55-9149-25bb7b620e56.png)
![image](https://user-images.githubusercontent.com/68924563/207717243-8ea8fe95-0612-429e-846e-cfd81095ae09.png)

#### Mobile Phone
![image](https://user-images.githubusercontent.com/68924563/207721060-99613e5b-f60e-4633-bc7c-93b729f20cb8.png)

### Wakatime

![image](https://user-images.githubusercontent.com/68924563/207717479-d6df920c-9158-4bd5-8409-96d75731f0e1.png)

## Integrantes:
     - Andrés Felipe Prieto Alarcón
     - Paula Julieth Cardozo Ferreira

@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmos PSEInt
Calificación: 100%
Retroalimentación: Excelente trabajo!

# Tarea Página Pokedex
Calificación: 110%
Retroalimentación: Excelente! Se tiene encuenta la inclusión de interacciones funcionales con JavaScript como el consumo de los datos de la API de Pokemon y el uso de Glider.
