### ISSUE TITLE
Proyecto sprint 2

### ISSUE THREAD

**Issue by manuelRestrep0** [MAKAIABootcamp/fundamentos-back1#40]
## 
Pagina inicio
![image](https://user-images.githubusercontent.com/94997816/211415020-14eec0d9-950b-45d2-8016-1794740235d8.png)
Pagina agregar video
![image](https://user-images.githubusercontent.com/94997816/211558967-e4ce1c4e-e862-485d-8cfd-43c021a2dcb5.png)
Pagina reproductor de video
![image](https://user-images.githubusercontent.com/94997816/211559048-d9913437-27d3-45cf-90c9-bd573ac022f6.png)

## 
![image](https://user-images.githubusercontent.com/94997816/211415090-5a659355-8a26-4112-bd4d-4e1377ced589.png)

por: @manuelRestrep0

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo!
