### ISSUE TITLE
workshop 2

### ISSUE THREAD

**Issue by manuelRestrep0** [MAKAIABootcamp/fundamentos-back1#41]
##
![image](https://user-images.githubusercontent.com/94997816/211416643-7c90d581-e471-4a79-949a-9265f1d11a9d.png)
##
![image](https://user-images.githubusercontent.com/94997816/211416693-0a01e293-366b-4032-adf5-e0739795cf9a.png)

Por: @manuelRestrep0

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
88%
### Retroalimentación
Faltó la funcionalidad de actualizar información de un producto, la aplicación solo permite eliminar el último producto de la lista.
