### ISSUE TITLE
Entrega Proyecto Sprint 2

### ISSUE THREAD

**Issue by BrianStevenV** [MAKAIABootcamp/fundamentos-back1#42]
[URL DEL REPOSITORIO] https://github.com/BrianStevenV/Project-Sprint-2
[URL DEL VERCEL PAGES] https://project-sprint-2.vercel.app/index.html

Para desarrollar el proyecto Sprint 2, se realizo con la informacion suministrada en clase mas tiempo de auto estudio.
![foto_principal](https://user-images.githubusercontent.com/119947948/211431753-59fd7090-1bdc-46c1-920e-c20a882c5a21.png)
En esta primera captura, podemos ver el proyecto en su pagina principal.
![foto_botones](https://user-images.githubusercontent.com/119947948/211431794-4fa5b74b-13e5-4a9f-b0e7-32cf40217012.png)
En esta segunda captura, vemos el funcionamiento de los botones de filtrado
![foto_formulario](https://user-images.githubusercontent.com/119947948/211431822-08b577c9-7937-4b84-85af-3f1da5e37572.png)
En esta tercera captura, vemos un formulario donde se agrega videos, (vemos que estamos agregando un video)
![foto_addPage](https://user-images.githubusercontent.com/119947948/211431888-f17804d5-7f7a-45e3-b3e8-11c741f1b46b.png)
En esta cuarta captura, vemos como satisfactoriamente se agrega el video a la pagina principal y funciona con los botones de filtrado
![foto_reproductor](https://user-images.githubusercontent.com/119947948/211431950-9f820b4a-95b8-4384-a804-abe533a4bbec.png)
Y aqui podemos ver el reproductor
![foto_waka](https://user-images.githubusercontent.com/119947948/211431973-7871f77c-4e52-4119-8229-a332d8884a17.png)
por: Brian Steven Acevedo Villegas
@WhitneySt

**Comment by BrianStevenV** [comment]
Error en git pages

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente interfax. **Nota**: En el despliegue de la página no permite la re dirección a la página de detalles del video.
