### ISSUE TITLE
Workshop 2

### ISSUE THREAD

**Issue by BrianStevenV** [MAKAIABootcamp/fundamentos-back1#43]
[URL REPOSITORIO] https://github.com/BrianStevenV/Reto-02
[DESPLIEGE] https://workshop002.vercel.app/
![foto_main](https://user-images.githubusercontent.com/119947948/211460140-ea08ccb5-ec3a-422f-8ffd-f00c726f4e46.png)
Imagen principal.
![foto_form](https://user-images.githubusercontent.com/119947948/211460186-4d248ce9-805e-4299-8022-757bf04c1183.png)
Foto formulario
![foto_funcionamiento](https://user-images.githubusercontent.com/119947948/211460997-3228d355-c461-4c4e-9a09-59bb60649419.png)
![waka](https://user-images.githubusercontent.com/119947948/211461094-34ad366c-0a3c-497c-88b7-ca18378b7907.png)
by: Brian Steven Acevedo Villegas
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
77%
### Retroalimentación
Completada las funcionalidades de crear y pintar los productos; sin embargo, no se completó las acciones de eliminar y actualizar productos.
