### ISSUE TITLE
Workshop Sprint 2

### ISSUE THREAD

**Issue by salazar3148** [MAKAIABootcamp/fundamentos-back1#44]
# Descripcion
El usuario puede añadir productos a su lista, sus caracteristicas son: Nombre, Precio, Cantidad Y Categoría.

Posteriormente podrá decidir si eliminar, o editar cada producto de su tabla ya que consigo lleva 2 columnas que implemetan dichas funcionalidades

## WakaTime
![Screenshot from 2023-01-10 01-54-25](https://user-images.githubusercontent.com/105958626/211482056-2e20afc8-da19-4a52-b625-a0f16d22f9a4.png)
![Screenshot from 2023-01-10 01-55-03](https://user-images.githubusercontent.com/105958626/211482184-c6a35140-cacb-4e56-a2c4-f85d7a6406e1.png)

# WorkShop Sprint 2:  [Repositorio](https://github.com/salazar3148/Workshop-Sprint-2)
# Despliegue: [URL](https://salazar3148.github.io/Workshop-Sprint-2/) 

#### Hecho por Christian David Salazar Marulanda
# @WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo!
