### ISSUE TITLE
Entrega workshop 2 sprint

### ISSUE THREAD

**Issue by sofmillan** [MAKAIABootcamp/fundamentos-back1#45]
## URL del repositorio: [Tabla de productos](https://github.com/sofmillan/CRUDJS)
**Github pages:** [Page](https://sofmillan.github.io/CRUDJS/)
## Descripción:
Este proyecto consiste en un crud local a base de javascript en el que se pueden añadir, eliminar y editar productos que se muestran en una tabla.

## Imagen de la vista
<img width="681" alt="image" src="https://user-images.githubusercontent.com/98916125/211642699-be478d1c-6f44-4139-9b7a-c0d0a9f524af.png">

## Estadísticas de Wakatime
<img width="594" alt="image" src="https://user-images.githubusercontent.com/98916125/211643823-bd7103e5-eb7f-4976-8781-d02b8ee07f4b.png">

**Hecho por:** Sofía Millán 
**Usuario:** sofmillan

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente Interfaz!
Código muy bien organizado
