### ISSUE TITLE
Entrega Proyecto Sprint 2

### ISSUE THREAD

**Issue by VivianaGuzmanBuritica** [MAKAIABootcamp/fundamentos-back1#46]
## Descripción de la entrega 
Desarrollo de una aplicación en JavaScript la cual permite siguientes tareas:
1.Al realizar click sobre una card de cualquier video, debe dirigir al usuario a la página de detalles del elemento.
2.Funcionalidad de los botones de filtrado por categoría
3.Construir una página con un formulario que permita agregar un nuevo video, junto con las validaciones en JavaScript para convertir todos los inputs requeridos.
4.En el aplicativo debe mostrar como mínimo 30 cards de video y reproducir como mínimo 10 videos.

![image](https://user-images.githubusercontent.com/82985780/211657916-a20cfbb4-23ff-47ef-8df3-e4e401f67ba5.png)
![image](https://user-images.githubusercontent.com/82985780/211658772-7e06b2ba-fceb-4bac-8941-7bc2218be064.png)

## URL[Wakatime](https://wakatime.com/dashboard)
![image](https://user-images.githubusercontent.com/82985780/211658296-b6352552-e131-4c4f-a26d-268b69a04dfd.png)

### Viviana Guzman Buriticá
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación:
100%
### Retroalimentación
Excelente Interfaz! 
**Nota**: En el despliegue de la página no permite la redirección a la página de detalles del video.
