### ISSUE TITLE
Entrega Proyecto 2 Sprint

### ISSUE THREAD

**Issue by sofmillan** [MAKAIABootcamp/fundamentos-back1#47]
## Descripción:
Este proyecto consiste en una página de videos, en la cual se pueden añadir, eliminar y hacer búsquedas por título.
## Imagen de la vista
<img width="674" alt="image" src="https://user-images.githubusercontent.com/98916125/211670516-8649e8c2-3aed-4284-b4a7-07a27bd2a279.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/98916125/211670977-9e9740bf-1530-45a4-9734-fb5d9d2ec172.png">

## Estadísticas de Wakatime
<img width="599" alt="image" src="https://user-images.githubusercontent.com/98916125/211670667-7760fd87-f63d-4d62-9109-c7d2b17881f1.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/98916125/211670692-9f0858b0-de5a-406f-89b3-3447c2b92bde.png">

Hecho por: Sofía Millán
Usuario: sofmillan

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
112%
### Retroalimentación
Excelente trabajo! De las funcionalidades plus: realizó la búsqueda de videos por nombre y eliminar un video.
Código muy bien organizado.
