### ISSUE TITLE
Proyecto Sprint 2 

### ISSUE THREAD

**Issue by EnriquePinzon** [MAKAIABootcamp/fundamentos-back1#48]
**URL a** [Mi repositorio GitHub](https://github.com/BryanPinzon/Proyecto-Sprint-2-)
**URL a** [Despliegue del aplicativo VideoTube](https://proyecto-sprint-2-1wt2jp4pr-bryanpinzon.vercel.app/)

**Descripción de la entrega.** 
Desarrollo de una aplicativo en HTML, CSS y JavaScript la cual nos permite:
1. Al realizar click sobre una card de cualquier video, debe dirigir al usuario a la página de detalles del vídeo tales como su reproducción y lista de vídeos sugeridos.
2. Funcionalidad de los botones de filtrado por categoría (Música, Programación, Diseño UX)
3. Construir una página con un formulario que permita agregar un nuevo video, junto con las validaciones en JavaScript para convertir todos los inputs requeridos.
4. En el aplicativo debe mostrar como mínimo 30 cards de video y reproducir como mínimo 10 videos.

![imagen](https://user-images.githubusercontent.com/114439510/211683908-72d04a62-4b0c-4d5a-841e-0260a7bade01.png)
![imagen](https://user-images.githubusercontent.com/114439510/211683949-913bddcf-942f-424d-a3d1-b67bff412293.png)
![imagen](https://user-images.githubusercontent.com/114439510/211683989-b61113e6-3c6e-41f3-819e-c709a40186ba.png)
![imagen](https://user-images.githubusercontent.com/114439510/211684216-9dc9fd34-8dd4-4371-aeb1-11761e4a3d63.png)

**URL a** [Dashboard Wakatime](https://wakatime.com/dashboard?start=2023-01-04&end=2023-01-10)

**Brayan Enrique Pinzón Quiñonez**

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
98%
### Retroalimentación

1. No es posible acceder a las estadísticas de Wakatime
2. Excelente interfaz
3. En el despliegue de la página, cuando redirecciona a la página de detalles del video no es visible el componente de visualización de videos.
