### ISSUE TITLE
Proyecto sprint 2

### ISSUE THREAD

**Issue by Strugtter** [MAKAIABootcamp/fundamentos-back1#49]
# url repositorio: [Reproductor de video](https://github.com/Strugtter/sprint_2.git)
# Desarrollo técnico: Se empleo la funciones Arreglos y objetos, Eventos(.addEventListener, Métodos de arreglos, Objeto Storage (localStorage y/o sessionStorage), Responsive  design.
# Despliegue: [Reproductor de videos](https://strugtter.github.io/sprint_2/)
# Imagenes
![Main](https://user-images.githubusercontent.com/106613231/212164157-37deb6c1-be3c-4fa8-98bd-a29183887396.JPG)
![Detalles](https://user-images.githubusercontent.com/106613231/212164186-4371160f-5d4e-436b-ab51-928ecbe105cd.JPG)
![AddVideo](https://user-images.githubusercontent.com/106613231/212164203-c52663cd-f2a7-47fb-808e-f02fee31c37f.JPG)
# WakaTime
![WakaTime](https://user-images.githubusercontent.com/106613231/211708758-4580ca67-12d6-4ff1-9470-a523bb6d7f61.JPG)
# integrante: Camilo Andrés Botina Trujillo
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
105%
### Retroalimentación
Muy buen trabajo. En la calificación se tiene en cuenta el desarrollo de la funcionalidad bonus búsqueda de video por nombre.
Se recomienda ajustarse a los estilos de la página, cuando se proporciona un diseño UI.
