### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by EmmanuelUs4** [MAKAIABootcamp/fundamentos-back1#5]
## Explicación del desarrollo técnico

Desarrollo de una interfaz de Pokedex con nombre "Poketeka". Está dividido en tres partes, header, donde iría el título de Poketeka junto al logo; main, que encierra la toda la información del pokemon; y el footer, donde se disponen los demás pokemones disponibles en la base de datos de la pokedex.

## Imagen de las vistas
![pokedex](https://user-images.githubusercontent.com/120135105/207721799-b3890656-2085-4f8b-9d76-d984370629d5.png)
## Estadísticas de Wakatime
![wakawaka](https://user-images.githubusercontent.com/120135105/207722278-1388f191-b3be-477d-a540-88593153eebd.png)
## Integrantes
Emmanuel Usme
Brian Steven

## Ejercicios PSeint

https://drive.google.com/drive/folders/1mRR_CaPiqwVSwbEknMeRgmJsqb5CMT54?usp=sharing

@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmos PSEInt
Calificación: 100%
Retroalimentación: Con este 2do issues entregado, se realiza el ajuste de la calificación de la tarea (En el segundo issues, se evidencia la corrección en el algoritmo productos, se calcula el iva de los productos con diferentes porcentajes).

# Tarea Pokedex
Calificación: 97%
Retroalimentación: Se observa ajustes en los estilos (No hay desborde de los textos en los elementos contenedores); sin embargo, no se entrega la URL de despliegue con los nuevos ajustes. Muy buen trabajo!
