### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by salazar3148** [MAKAIABootcamp/fundamentos-back1#50]
# Características
- Plataforma para publicar videos de Música, Programación y Desarrollo BackEnd

- Contiene Tags para Filtrar los videos por Categoría

- Implementa una barra de búsqueda para encontrar contenido por palabras clave

- Cada persona puede publicar un video, haciendo uso de un formulario que se encuentra en pie de pagina.

# Sprint 2:  [Repositorio](https://github.com/salazar3148/Sprint-2)
# Despliegue: [URL](https://salazar3148.github.io/Sprint-2/) 

# WakaTime
![image](https://user-images.githubusercontent.com/105958626/211715166-85bb8c47-1875-4f01-96ce-b926a2ece1fa.png)
![image](https://user-images.githubusercontent.com/105958626/211715228-dd336132-cba3-4d05-9354-49de1fea8064.png)

#### Hecho por Christian David Salazar Marulanda
# @WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
106%
### Retroalimentación
Excelente interfaz!
