### ISSUE TITLE
Workshop2

### ISSUE THREAD

**Issue by EnriquePinzon** [MAKAIABootcamp/fundamentos-back1#52]
**Url a** [Repositorio](https://github.com/BryanPinzon/Workshop2)

**Url a** [Despliegue](https://workshop2-9g7w.vercel.app/)

Descripción del desarrollo:  Se usó lo aprendido en HTML,CSS, y el manejo del DOM.
![imagen](https://user-images.githubusercontent.com/114439510/211718937-0307deec-1dcc-4b01-b915-964f711d14b6.png)
![imagen](https://user-images.githubusercontent.com/114439510/211719080-94262c0c-1791-4a9d-8b96-bf17739d818a.png)

![imagen](https://user-images.githubusercontent.com/114439510/211719189-952c4bd2-9788-4d71-8af8-0f6d7e749f47.png)

**Brayan Enrique Pinzon Quiñonez**

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
75%
### Retroalimentación
El aplicativo permite agregar productos y mostrar los productos en la tabla, sin embargo las acciones de eliminar y actualizar información de productos no están desarrolladas.
