### ISSUE TITLE
Entrega Proyecto Sprint #2

### ISSUE THREAD

**Issue by EmmanuelUs4** [MAKAIABootcamp/fundamentos-back1#53]
## URL Repositorio 
https://github.com/EmmanuelUs4/Proyecto-Sprint-2.git
## URL Git Pages 
https://proyecto-sprint-2-beta.vercel.app

## Explicación
Realización de un VideoTube, sus funcionalidades son:
Reproducir cualquier card al que se le haga click
Agregar un nuevo video
reproducción del video cliceado empleando session.storage
## Vistas
![image](https://user-images.githubusercontent.com/120135105/211719147-381540ea-1f91-404c-8ce2-77a68638fe66.png)
![image](https://user-images.githubusercontent.com/120135105/211719477-97e80272-b09a-4be6-bee2-82324086c58f.png)
![image](https://user-images.githubusercontent.com/120135105/211719545-5ebe4a25-5c39-43ef-a183-a91b8b794b78.png)

## Wakatime
![proyecto ss 1](https://user-images.githubusercontent.com/120135105/211718516-2a4a176c-d13b-48da-ba5c-b7188736903b.png)
![waka 2](https://user-images.githubusercontent.com/120135105/211718531-73ecc62a-5c25-4968-82bb-785ba060836b.png)

EmmanuelUs4 - Emmanuel Usme

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
100%
### Retroalimentación
Excelente trabajo. 
**Nota**:  Se recomienda ajustar los estilos del aplicativo al diseño UI suministrado.
