### ISSUE TITLE
Proyecto sprint 2

### ISSUE THREAD

**Issue by Pipe1098** [MAKAIABootcamp/fundamentos-back1#54]
## Descripcion:
Pagina web donde se usaron las funciones Arreglos y objetos, Eventos(.addEventListener, Métodos de arreglos, Objeto Storage (localStorage y/o sessionStorage) y otros aspectos vistos en la calse de fundamentos web.

![pagina](https://user-images.githubusercontent.com/90018701/211719104-86d39356-07b4-4993-9970-7faf88fd5f3a.png)

![ESTADISTICAS](https://user-images.githubusercontent.com/90018701/211721500-bfb44fbb-a5c6-43df-b0a2-9efd493077c2.png)

POR : Luis Felipe Penagos Bedoya

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
104%
### Retroalimentación
En la URL de despliegue no funciona la acción de eliminar video. En la calificación se tiene en cuenta la funcionalidades de ejecución parcial de edición de información y eliminar video.
Excelente trabajo!
