### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by dianaperezdv** [MAKAIABootcamp/fundamentos-back1#55]
[URL Repositorio de GitHub](https://github.com/dianaperezdv/Sprint2_MAKAIA)

**Descripción de la entrega.**
Desarrollo de una aplicativo en HTML, CSS y JavaScript la cual nos permite:

 Al realizar click sobre una card de cualquier video, debe dirigir al usuario a la página de detalles del vídeo tales como su reproducción y lista de vídeos sugeridos.
Funcionalidad de los botones de filtrado por categoría (Música, Programación, Diseño UX)
Construir una página con un formulario que permita agregar un nuevo video, junto con las validaciones en JavaScript para convertir todos los inputs requeridos.
En el aplicativo debe mostrar como mínimo 30 cards de video y reproducir como mínimo 10 videos.

Vistas: 
**INDEX GENERAL**
![image](https://user-images.githubusercontent.com/47093819/211722244-2db64269-f1c4-4abf-8591-26d90bad7cd7.png)

**FILTRADO**
![image](https://user-images.githubusercontent.com/47093819/211722336-60d50250-5b36-407d-bbca-e22780a5b4e2.png)

**FORMULARIO**
![image](https://user-images.githubusercontent.com/47093819/211722442-be914b46-4b49-4fcb-9545-65e377b6f1a7.png)

**REPRODUCTOR DE VIDEO**
![image](https://user-images.githubusercontent.com/47093819/211722118-5519dbac-c0d0-461b-881f-8ec7a5af0aa0.png)

**Wakatime**
![image](https://user-images.githubusercontent.com/47093819/211720485-67981bae-5b41-498d-9377-8fc16a4b6926.png)

Realizado por: Diana Camila Pérez del Valle
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
94%
### Retroalimentación
En el issues no fue suministrado la URL de despliegue.
Excelente interfaz!
