### ISSUE TITLE
Proyecto Sprint 2

### ISSUE THREAD

**Issue by ghost** [MAKAIABootcamp/fundamentos-back1#56]
# URL DEL REPOSITORIO: 
https://github.com/camilorestrepodev/Entrega-Sprint-2

# URL DEL DESPLIEGUE:
[URL](https://camilorestrepodev.github.io/Entrega-Sprint-2/)

## CONTENIDO DE LA WEB

- Etiquetas Html5: id, class, input, button
- Estilos(Css)
- Javascript: Array function, objects, localStorage
- Eventos DOM

# VISTAS:
## IMAGEN PRINCIPAL DE LA WEB
![1](https://user-images.githubusercontent.com/119947851/211721025-0a77c623-73d9-4811-b62a-6f383dfba866.png)

## IMAGEN POR FILTRACIÓN DE CATEGORIA
![2](https://user-images.githubusercontent.com/119947851/211721062-62caa53a-7aa3-4885-bf69-d56134259b52.png)

## IMAGEN DE FORMULARIO DE AGREGAR NUEVO VIDEO
![3](https://user-images.githubusercontent.com/119947851/211721106-118108dd-1971-4303-be06-f9d48b4d8467.png)

## WAKATIME
![4](https://user-images.githubusercontent.com/119947851/211721714-e9be8ab2-0d71-4439-bb0f-bb8ac778e885.png)

## Presentado por:
Juan Camilo Restrepo B.

**Comment by WhitneySt** [comment]
### Calificación
99%
### Retroalimentación
En la URL de despliegue suministrada en el issues, no se encuentra disponible la acción ni la interfaz de agregar nuevo video.
