### ISSUE TITLE
Workshop Sprint 2

### ISSUE THREAD

**Issue by EmmanuelUs4** [MAKAIABootcamp/fundamentos-back1#57]
## URL repositorio 
https://github.com/EmmanuelUs4/workshop-2.git
## URL GitPages
https://workshop-2-one.vercel.app/pages/formulario.html
## Explicación
Realización de un programa que permita agregar productos a una tabla, guardando los datos en session storage e imprimiendolos en otra página 

nota: Realicé este ejercicio en Windows 7, al realizar el issue por alguna razón no actualizó los cambios en la página principal, por lo que está incompleto.
## Vistas
![reto vista](https://user-images.githubusercontent.com/120135105/211722429-2d5892b6-b4c5-4e1a-b992-23ea82c4b47f.png)

## Wakatime

![retoreto](https://user-images.githubusercontent.com/120135105/212178631-19bc5fda-bcc8-4600-b465-91ddae37ecc3.png)
EmmanuelUs4 - Emmanuel Usme

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
96%
### Retroalimentación
1. La URL de despliegue no se encuentra disponible
2. Excelente interfaz
