### ISSUE TITLE
Entrega Sprint2

### ISSUE THREAD

**Issue by Jaime-U-Lopez** [MAKAIABootcamp/fundamentos-back1#58]
# Entrega sprint2

## Descripción Técnica :

El trabajo es la emulación de la pagina de Youtube, en el cual realizamos la implementación de Javascript, html. css, con la unión de array y pantallas, formularios y sessionStorage.

En el cual realizamos un crud de los videos.

Imagen:

proyecto:

![image](https://user-images.githubusercontent.com/50783391/211926029-074e01c8-4556-4d53-8438-fb1eb5ab5dcf.png)

Wakatime: 

![image](https://user-images.githubusercontent.com/50783391/211925700-962cf50a-c498-4399-885f-bd07e1441272.png)

![image](https://user-images.githubusercontent.com/50783391/211925867-8c0a539a-cb96-4c87-b54a-a5d94949f750.png)

Por: Jaime Orlando Lopez

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
109%
### Retroalimentación
URL de despliegue no disponible. Se tiene en cuenta en la calificación las funcionalidades extras: Búsqueda de video por nombre, editar información y eliminar video.
