### ISSUE TITLE
Workshop Sprint 2

### ISSUE THREAD

**Issue by afprietoa** [MAKAIABootcamp/fundamentos-back1#59]
## Desarrollo técnico:

Se creo un formulario para agregar un producto con foto, nombre, precio, descripción, cantidad y categoría.  Al guardar, el producto es añadido a un array de productos base donde estén enlistado todos los productos en una tabla.

### Website Screenshots

![image](https://user-images.githubusercontent.com/68924563/212207082-0cd5f067-42c7-44d2-84af-652c65cee2c7.png)
![image](https://user-images.githubusercontent.com/68924563/212207137-c12489fe-9240-4122-9aed-dc0da55840f1.png)

### Wakatime

![image](https://user-images.githubusercontent.com/68924563/212207269-132bcb5c-0850-4b2c-88fe-4abd908e54f8.png)

## Integrante:
     - Andrés Felipe Prieto Alarcón

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
75%
### Retroalimentación
Excelentes interfaz. Se encuentran funcionales las acciones de crear nuevo producto y mostrar listado de productos. No se encuentra desarrollo de las acciones de eliminado y edición de la información de productos.
