### ISSUE TITLE
Entrega Workshop 1 Sprint

### ISSUE THREAD

**Issue by imsntiago** [MAKAIABootcamp/fundamentos-back1#6]
## Explicación Desarrollo Técnico 
Creación de una Pokedex, donde se utilizaron lenguajes de marcado como HTML5 para desarrollar la estructura como el header, main y footer y el uso de CSS3 para darle estilos y efectos. También se implemento Flexbox para hacer el sitio web adaptable a dispositivos mobiles.
## Vista Pokedex
![image](https://user-images.githubusercontent.com/120517759/207731669-696e7ff2-8246-49ac-b9f4-f8bf2a05352f.png)
## Taller Pseint
Fueron desarrollados en el lenguaje de programación Javascript
https://drive.google.com/drive/folders/12wOm3riJGt_QUzaJsHEZ2uMnDP74xz8i?usp=share_link
## Integrantes: 
Santiago Jaramillo
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 100%
Retroalimentación: Muy buen trabajo!
# Tarea Pokedex
Calificación: 100%
Retroalimentación: Excelente!
