### ISSUE TITLE
Proyecto sprint 2 videotube

### ISSUE THREAD

**Issue by Edward-Reyes-Vanegas** [MAKAIABootcamp/fundamentos-back1#60]
## Explicación del desarrollo técnico
Esta es una aplicacion donde se aprende desarrollo html css y funcionalidad de una pagina local storage y sesion storage
![Diapositiva1](https://user-images.githubusercontent.com/120218145/212207608-5252318d-8b85-4dd6-9d7f-0a9855e56be0.JPG)
![Diapositiva2](https://user-images.githubusercontent.com/120218145/212207612-242b2f47-4ebc-4af2-b52e-6434c1e4b9f3.JPG)
![Diapositiva3](https://user-images.githubusercontent.com/120218145/212207613-fbce026c-c5e1-4fb6-8241-b52b5a6b23a3.JPG)

@Edward-Reyes-Vanegas 
## Imagen de las vistas
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
76%
### Retroalimentación
En el issues no fue suministrada la URL de despliegue del aplicativo. 

Se recomienda organizar los archivos de los proyectos con la siguiente estructura:
> 1. **Carpeta `assets`**: En esta carpeta deben ir todos los recursos auxiliares para construir las aplicaciones. Por ejemplo: imágenes
> 2. **Carpeta `styles`**: Esta carpeta debe contener todos los archivos CSS. Por ejemplo: style.css
> 3. **Carpeta `scripts`**: Esta carpeta debe contener los scripts o archivos JavaScripts (con estensión `.js`) vinculados directamente a un archivo` .html` en el atributo `src` de una etiqueta `<script>`
> 4. **Carpeta `pages`**: Esta carpeta debe contener los archivos `.html` (o páginas del aplicativo) secundarios. Por ejemplo: `addNuevoVideo.html`
> 5. **Archivo `index.html`**: Este es el archivo `.html `principal
