### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by sebastian1695** [MAKAIABootcamp/fundamentos-back1#61]
En este Sprint se programó mediante js con diseño de css en una página html, se usaron elementos DOM, funciones, arreglos, objetos y funcionalidad 
[https://github.com/sebastian1695/Sprint-2.git](url)

WAKATIME :
![Screen Shot 2023-01-12 at 8 10 18 PM](https://user-images.githubusercontent.com/119948037/212214526-c16b0793-cfae-4258-917a-d
![Screen Shot 2023-01-12 at 8 10 18 PM](https://user-images.githubusercontent.com/119948037/212214639-8c24b9fb-d94b-4a49-b340-b14909952abe.png)
d1dbf91777b.png)

Imagen del aplicativo:
![Screen Shot 2023-01-12 at 8 17 24 PM](https://user-images.githubusercontent.com/119948037/212214917-28ecc183-83cb-4641-8b38-ea86bbdea5ee.png)
![Screen Shot 2023-01-12 at 8 17 35 PM](https://user-images.githubusercontent.com/119948037/212214925-8e82a805-31d0-4e61-b0a4-2b375c107174.png)

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
68%
### Retroalimentación
El aplicativo desarrollado no es coherente con el asignado en el Proyecto de sprint 2; sin embargo, se califican los requerimientos funcionales y técnico que están sujetos a evaluación con el ejercicio del proyecto.
En la issues no se proporciona URL de despliegue.
