### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by Rmazov** [MAKAIABootcamp/fundamentos-back1#62]
videotube spring 2
https://github.com/Rmazov/Sprint2

![wkatime111](https://user-images.githubusercontent.com/97861713/213052900-b65eba08-22f3-40e4-9e1a-1c04b4ebb948.jpg)

![image](https://user-images.githubusercontent.com/97861713/213055014-92dcb6db-64ad-41ef-8b9b-75da052d010c.png)

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
109%
### Retroalimentación
1. En la issues no se proporciona la URL de despliegue
2. En la calificación se tiene en cuenta las funcionalidades bonus desarrolladas: Búsqueda de videos por nombre o título, editar información del video y eliminar video.
3.  Muy buen trabajo, Felicitaciones!
