### ISSUE TITLE
Entrega Sprint 3

### ISSUE THREAD

**Issue by Strugtter** [MAKAIABootcamp/fundamentos-back1#63]
# url repositorio : [Inmobiliaria](https://github.com/Strugtter/sprint3.git)
# Despliegue: [Pages](https://strugtter.github.io/test/)
# Explicación ténica: Desarrollo de una pagina de inmobiliaria, Empleando JSON-SERVER con simulador de una API -REST, realizados peticiones atraves de los metodos HTTPs get,post,put y delete. 
# Imagen de sitio web:
# Principal
![main_part1](https://user-images.githubusercontent.com/106613231/213369355-61ae8743-49f7-464b-84dc-b436857b1078.JPG)
![main_part2](https://user-images.githubusercontent.com/106613231/213364409-4ea869c8-3c66-45fd-818e-c8c843edbc5a.JPG)
# Agregar propiedad
![Add_property](https://user-images.githubusercontent.com/106613231/213301069-0d8b78ac-ffa1-420c-b00d-f0e3d2a03a84.JPG)
# Detalles de la propiedad
![DetailsProperty](https://user-images.githubusercontent.com/106613231/213301150-27f7dc99-17db-4482-806c-9af3bc10a1b2.JPG)
# Favoritos
![favorite_Property](https://user-images.githubusercontent.com/106613231/213353643-7da329dc-d589-4395-84b6-b104b701e911.JPG)
# Actualizar
![UpdateProperty](https://user-images.githubusercontent.com/106613231/213301389-7f34df61-f5a1-4ac6-8530-e92663ba5a37.JPG)
# WakaTime
![WakaTimePart1](https://user-images.githubusercontent.com/106613231/213302209-8d074f8d-6207-43d5-bec3-65f8cff500f2.JPG)
![WakaTimePart2](https://user-images.githubusercontent.com/106613231/213302225-d6cb95c7-323e-447a-b7a4-133965ce245f.JPG)
# Integrante 
Camilo Andres Botina
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
104%

### Retroalimentación
Excelente trabajo. Se tiene en cuenta en la calificación la funcionalidad extra de crear nuevo inmueble. 
**Nota**: Los módulos no es necesario que sean enlazados en los archivos`.html`
![image](https://user-images.githubusercontent.com/98284374/214146223-19957e14-97f9-4624-bc53-48fc543c5cfa.png)
