### ISSUE TITLE
json-server

### ISSUE THREAD

**Issue by Rmazov** [MAKAIABootcamp/fundamentos-back1#64]
https://github.com/Rmazov/sprint3-json-server
![wakatijson](https://user-images.githubusercontent.com/97861713/213306943-04f92b6e-6c22-416f-8b38-6d13d783b8a1.png)
![image](https://user-images.githubusercontent.com/97861713/213307462-a594e8bc-ff24-446f-b8a7-336a931c378e.png)
![image](https://user-images.githubusercontent.com/97861713/213307587-94ba76ce-57e3-4b13-a470-515989213802.png)

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
103%
### Retroalimentación
En la calificación se tiene en cuenta el desarrollo de la funcionalidad adicional (Crear un nuevo inmueble).
Es una buena práctica reutilizar código que ya ha sido desarrollado, sin embargo no es una buena práctica asignar (o dejar asignado) nombres a las variables, constantes y funciones que no guarden una coherencia o relación alguna con la aplicación que se esté desarrollando.
