### ISSUE TITLE
Entrega Sprint 2

### ISSUE THREAD

**Issue by afprietoa** [MAKAIABootcamp/fundamentos-back1#65]
# Youtube Clone

URL GitHub Repository: [Youtube Clone Repository](https://github.com/afprietoa/YoutubeClone.git)
URL GitHub Pages: [Youtube Clone Deployment](https://afprietoa.github.io/YoutubeClone)

## Explicación técnica

Se construyo una págine web con un diseño responsive, la interfaz aparente a la página de Youtube, se hizo el consumo de la API de Youtube,  se carga 30 videos y reproduce cada uno, asi mismo se permite la busqueda.

## Lista de videos
![image](https://user-images.githubusercontent.com/68924563/213310915-2a8f1ce0-a053-437f-a6f6-c094049fc9fb.png)

## Reproductor de videos
![image](https://user-images.githubusercontent.com/68924563/213310997-c089994b-4556-4654-9083-1110ba675842.png)

## Wakatime
![image](https://user-images.githubusercontent.com/68924563/213310768-74c14f41-121d-445b-b35c-863efc0bfe53.png)

### Integrante
- Andrés Prieto

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
83%
### Retroalimentación
Muy buen aplicativo. No se evidencia desarrollo de la funcionalidad de agregar nuevo video, los botones de filtrado no están en funcionamiento y se tiene en cuenta el desarrollo de la funcionalidad de búsqueda por nombre o título del video.
