### ISSUE TITLE
Entrega proyecto Sprint 3

### ISSUE THREAD

**Issue by sofmillan** [MAKAIABootcamp/fundamentos-back1#66]
## Explicación del desarrollo técnico
Este proyecto consiste en una página de inmuebles, en la  cual manipulamos datos mediante json server, por lo que se pueden eliminar, editar y agregar propiedades, así como búsquedas por tipo de inmueble y por ubicación. Igualmente cuenta con una sección de favoritos y página de detalles.

## Imagen de la vista
<img width="950" alt="image" src="https://user-images.githubusercontent.com/98916125/213340363-9063ea07-a18f-4d8a-a20d-11c04651e4f8.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/98916125/213340425-c7227f2c-3278-44a4-9107-d770f50721d4.png">

## Estadísticas de wakatime

<img width="823" alt="image" src="https://user-images.githubusercontent.com/98916125/213340548-85dca9ee-1dc7-49be-b317-8fae48564c57.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/98916125/213340640-7b54b0be-3aef-40c0-9f47-b12e67915062.png">

<img width="814" alt="image" src="https://user-images.githubusercontent.com/98916125/213341125-fc6ac435-eca0-49fc-a223-d62bbe85d6a7.png">

**Hecho por:** Sofía Millán
**usuario:** sofmillan

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
108%
### Retroalimentación
Excelente aplicativo.
**Nota**: Para que en la página de despliegue del proyecto reconozca los datos del json server, estos deben ser desplegados en un hosting como railways.
