### ISSUE TITLE
Entrega Sprint03

### ISSUE THREAD

**Issue by BrianStevenV** [MAKAIABootcamp/fundamentos-back1#67]
[URL REPOSITORIO} https://github.com/BrianStevenV/Sprint03
[URL VERCEL] https://sprint03-rho.vercel.app/
El aplicativo adquiere su informaicon por medio de JSON server, el cual utiliza para pintar, agregar a favoritos, filtrar, etc. Cumple con a funcion de filtrar por el input con enter, cumple con el requerimiento de agregar a favoritos y la funcion de ver detalles.
 
![foto1](https://user-images.githubusercontent.com/119947948/213353892-a1405d91-9913-42dc-9ff6-32c50afdd2d5.png)
![foto2](https://user-images.githubusercontent.com/119947948/213353899-5c2391d8-6da3-43e6-992b-d68571024cad.png)
![foto3](https://user-images.githubusercontent.com/119947948/213353906-fffd1d6b-011f-4d6e-b80f-a2e17af9db53.png)
![foto4](https://user-images.githubusercontent.com/119947948/213353912-99ba40c7-956a-4831-b0ce-3192ba80041d.png)
![foto 5](https://user-images.githubusercontent.com/119947948/213353921-3162fb83-a57b-43e4-8348-adb5445ed8c5.png)
![waka3](https://user-images.githubusercontent.com/119947948/213353928-261f14e2-633e-47d8-a00a-281840e381c6.png)
-----------------------------------------------------
ACTUALIZACION
![image](https://user-images.githubusercontent.com/119947948/213839879-bf6471d5-3e05-403b-ba69-13714381086a.png)
![image](https://user-images.githubusercontent.com/119947948/213839891-371c7635-a50b-4396-b291-df387742880e.png)
![image](https://user-images.githubusercontent.com/119947948/213839904-45dd0f90-cba8-4023-a613-7c8d69c201a7.png)
Se añadieron las funcionalidades de Delete en la seccion de favoritos y Edicion en las cards principales, como se puede apreciar en las imagenes.
![upd_wakatime](https://user-images.githubusercontent.com/119947948/213839958-4e018cb5-7e1d-43bc-99c7-7909c5c81c78.png)
Actualizacion del WakaTime
By: Brian Steven Acevedo Villegas
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
92%
### Retroalimentación
Se observa comentada la línea de código donde se ejecuta la función de filtrado.
**Nota**: Para que los datos de json-server estén disponibles en la página de despliegue, se deben desplegar estos datos (back) en un hosting como railways.
