### ISSUE TITLE
Entrega Sprint 3

### ISSUE THREAD

**Issue by manuelRestrep0** [MAKAIABootcamp/fundamentos-back1#68]
## Pagina de inicio
![image](https://user-images.githubusercontent.com/94997816/213358992-4d8f1a68-a078-4358-b5f4-91c65baed1ff.png)
## Pagina de detalles 
![image](https://user-images.githubusercontent.com/94997816/213359079-95d88d35-dd74-4d6e-a192-4202e008e808.png)

## wakatime
![image](https://user-images.githubusercontent.com/94997816/213359167-4686a964-6ba5-4b54-9759-0dd6584f52d0.png)

por: @manuelRestrep0

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
95%
### Retroalimentación
Aplicactivo funcionalmente completo. Faltó desarrollar los estilos en las interfaces.
