### ISSUE TITLE
Entrega proyecto Sprint 3

### ISSUE THREAD

**Issue by EmmanuelUs4** [MAKAIABootcamp/fundamentos-back1#69]
## URL del repositorio
https://github.com/EmmanuelUs4/Proyecto-3
## UR del Aplicativo
https://proyecto-3-tawny.vercel.app
## Explicación del desarrollo
Creación de una página de venta inmobiliaria, con funciones tales como:
-Input de búsqueda.
-Botones de filtrado entre tipo de vivienda y el estado.
-Añadir a favoritos
-Página de detalles de la propiedad
## Imágenes del aplicativo
![image](https://user-images.githubusercontent.com/120135105/213480790-3ab79711-979a-48d5-82de-f825bc2be7c9.png)
![image](https://user-images.githubusercontent.com/120135105/213484166-62c7583f-f81c-486e-97d5-5da181e726f5.png)
![image](https://user-images.githubusercontent.com/120135105/213484192-20dc0376-225b-40c7-b2dc-a63b3342d53f.png)
![image](https://user-images.githubusercontent.com/120135105/213484227-f7bef262-9ca2-4b3c-b89c-a8a39cbbba5b.png)
![image](https://user-images.githubusercontent.com/120135105/213484317-fe32c419-ceae-4c5f-8d86-f09f1f413167.png)
![image](https://user-images.githubusercontent.com/120135105/213484398-c7d4304b-70ca-4920-98c9-0b1fed160185.png)
![image](https://user-images.githubusercontent.com/120135105/213484452-68360417-b639-455f-99fa-db3526b40b99.png)
## Imágenes Wakatime
![1](https://user-images.githubusercontent.com/120135105/213484698-4b63d8c1-9e89-4710-83e0-a4967bc36e15.png)
![2](https://user-images.githubusercontent.com/120135105/213484717-6e2f36cf-056f-4b88-a8b6-986238d41d54.png)
![3](https://user-images.githubusercontent.com/120135105/213484738-341893cc-a354-4170-ba25-66f28faa4b43.png)
![4](https://user-images.githubusercontent.com/120135105/213484766-c840b05e-426e-4d62-a6e8-905b3a6ab93d.png)

## Realizado por
Emmanuel Usme - EmmanuelUs4

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
82%
### Retroalimentación
Excelente interfaz!. Hizo falta el desarrollo de las funcionalidades de editar y eliminar inmueble.
