### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by Jaime-U-Lopez** [MAKAIABootcamp/fundamentos-back1#7]
# URL Repositorio :[Ejercicio-1-entregable-en-Parejas](https://github.com/Jaime-U-Lopez/Ejercicio-1-entregable-en-Parejas/issues/1) 
## https://pokedexwebsite.netlify.app/
# Entrega Ejercicio Pokedex - Grupal 1 y Ejercicios de Psint
### Desktop:
![imagen Entera](https://user-images.githubusercontent.com/50783391/207737984-eda71044-4a5c-4219-9732-b6b3207d2cfd.png)

### Movil:
![movil2](https://user-images.githubusercontent.com/50783391/207738160-a421619c-b05c-4357-965d-53429f6a8128.png)
![movil1](https://user-images.githubusercontent.com/50783391/207738020-f252ebb3-0ad7-4e8a-bea5-7051cc28d29c.png)

## Wakatime:
![WakatimeDashBoard](https://user-images.githubusercontent.com/50783391/207738235-4e86664c-7459-41c9-b283-d3c01504151f.png)

![wakatimeProject](https://user-images.githubusercontent.com/50783391/207738247-7450da1e-e6b1-45d8-89d7-6c469d35b565.png)

# Entrega Psint

#### Enlace :
https://drive.google.com/drive/folders/10j1teMCozDq0PUpWwZ12b7bSpK3nVHcr?usp=sharing

#### Enlace :
https://drive.google.com/drive/folders/17TIGxVOSQQK87Nm4x1UDHANJnIkJG4yE?usp=sharing

## Integrantes:

https://github.com/Jaime-U-Lopez
https://github.com/sebastian1695

@sebastian1695
@Jaime-U-Lopez
@WhitneySt

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
## Calificación:
 Carlos Sebastián Rodriguez: 100%
 Jaime Urrego: 100%
# Tarea Pokedex
Calificación: 100%
