### ISSUE TITLE
Entrega Sprint 3

### ISSUE THREAD

**Issue by salazar3148** [MAKAIABootcamp/fundamentos-back1#70]
# Despliegue [CASAROYALE](https://salazar3148.github.io/Sprint-3/)

### Repositorio [mini-Back-end](https://github.com/salazar3148/mini-back-casaroyale)

# Principal
- Principalmente, se pueden ver las cards de los inmuebles publicados
- Filtrar por type, status y palabras clave
- Editar o eliminar un inmueble según sea la necesidad
- En el pie de pagina puedo publicar un nuevo inmueble o ir a la sección de favoritos

#### Hay 1 formulario que se muestra según lo que estoy haciendo (agregar - editar)
- Agregar: Puedo ingresar muchas imágenes sobre mi inmueble separando las URL's con comas, en el apartado dirección todos los detalles del inmueble y en la sección dueño todos sus datos incluyendo los de contacto.
- Editar: Lo anterior, además de mostrar los mensajes propios de que estoy en modo edición y  de llenar el formulario inmediatamente con la información que tenia anteriormente

#### Cada card cuenta con 3 botones adicionales
- Editar
- Eliminar
- Agregar como favoritos

### Favoritos
- Hay una pagina diferente en que me muestra todas las cards, que seleccione como favoritos

# Previsualización

## Filtrado
![image](https://user-images.githubusercontent.com/105958626/213485283-ca18c9d1-6108-44bf-844d-b51b7e2c27ce.png)

## Cards
![image](https://user-images.githubusercontent.com/105958626/213485435-cd63a0aa-ec29-46ea-a2f3-e7028f60b3b4.png)

## Favoritos
![image](https://user-images.githubusercontent.com/105958626/213486634-2f84c435-508d-417e-8081-1617b0543f01.png)

## Formulario
![image](https://user-images.githubusercontent.com/105958626/213486783-23704b62-c322-4df1-90db-b7b94fa038de.png)

## Pagina Detalle
![image](https://user-images.githubusercontent.com/105958626/213487742-736d718e-fd4b-49de-b94f-3c4b5a3b49c0.png)

# Wakatime
![image](https://user-images.githubusercontent.com/105958626/213488153-39fa79e0-e5be-4f27-b6a3-5da5a5431f31.png)

![image](https://user-images.githubusercontent.com/105958626/213488280-f937de39-5bad-42cc-879e-592c2339def0.png)

#### Hecho por Christian David Salazar Marulanda

# @WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
110%
### Retroalimentación
Excelente!! En la calificación se tienes en cuenta:
1. Desarrollo de la funcionalidad de agregar nuevo inmueble
2. Despliegue del json-server en railways

**Nota**: El atributo `id` de cada elemento debe ser único, al asignar un id sobre un elemento que se va a reproducir según la cantidad de datos disponibles en un array, ya este `id` no sería único.
