### ISSUE TITLE
Proyecto Sprint-3

### ISSUE THREAD

**Issue by Pipe1098** [MAKAIABootcamp/fundamentos-back1#71]
## Descripcion: 
Proyecto que implementa JSON-SERVER , peticiones HTTP con Fetch, gestion de promesas con async/await y los métodos GET, POST, DELETE y PUT , para crear una pagina web de una empresa inmobiliaria.

## Imagenes:
![paginainm](https://user-images.githubusercontent.com/90018701/213497430-db1e1769-502d-48bb-8c92-8230594b10d6.png)
![22](https://user-images.githubusercontent.com/90018701/213497577-9dd19fd7-6866-450a-9f29-97d5cc0979ce.png)
![23](https://user-images.githubusercontent.com/90018701/213497649-fe39ca09-c9ca-49fc-8c84-b98e9ed52bb5.png)

## Estadisticas:
![24](https://user-images.githubusercontent.com/90018701/213497803-123b5e72-30dc-4380-81b1-10f70cfd6c6c.png)

Por: Luis Felipe Penagos Bedoya

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
107%
### Retroalimentación
Excelente trabajo!
