### ISSUE TITLE
Entrega Spring 3

### ISSUE THREAD

**Issue by VivianaGuzmanBuritica** [MAKAIABootcamp/fundamentos-back1#72]
## Explicación del desarrollo
Creación de una página de venta inmobiliaria, con funciones tales como:
-Botones de filtrado entre tipo de vivienda..
-Añadir a favoritos
-Página de detalles de la propiedad
-Agregar, eliminar y editar una propiedad.

## Imágenes del aplicativo
![image](https://user-images.githubusercontent.com/82985780/213497487-42e2e40d-0196-45b5-a6e6-44335202ddce.png)

## Wakatime
![image](https://user-images.githubusercontent.com/82985780/213956044-91214bf3-bcb6-4d67-9592-0ec6095d8441.png)

## URL wakatime
https://wakatime.com/dashboard

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
90%
