### ISSUE TITLE
CasaRoyal - Sprint 3

### ISSUE THREAD

**Issue by EnriquePinzon** [MAKAIABootcamp/fundamentos-back1#73]
Repositorio GitHub [URL](https://github.com/BryanPinzon/Entrega-Sprint-3)
Despliegue aplicativo [URL](https://entrega-sprint-3.vercel.app/) 

Explicación del desarrollo. 
Creación de una página web tipo inmobiliaria para la venta y arriendo de casas y apartamentos.
Selección de filtrado por Casas, Apartamentos, en Venta, en Arriendo.
Filtrado del buscador por nombre de la ciudad de las viviendas.
Página y botón para añadir a favoritos. 
Página de detalles de la propiedad seleccionada en la card de imagen. 

![imagen](https://user-images.githubusercontent.com/114439510/213501674-37e6016e-3fec-4d0c-b8a6-e9af23db7930.png)
![imagen](https://user-images.githubusercontent.com/114439510/213502557-5e515dee-73f3-490c-b31e-b799198a7646.png)
![imagen](https://user-images.githubusercontent.com/114439510/213502736-e0c51b97-5cd8-4a6f-b3f2-27b683777ad4.png)
![imagen](https://user-images.githubusercontent.com/114439510/213502894-486bd2af-3e83-4a3c-8e42-c3693572471c.png)

**Filtrado**
![imagen](https://user-images.githubusercontent.com/114439510/213503532-cc3162d7-00f7-4d49-ae58-0837a24ff5b0.png)
**Favoritos** 
![imagen](https://user-images.githubusercontent.com/114439510/213503721-d76e0386-4c02-4b7c-977b-7b0afa6468f2.png)
**Detalles**
![imagen](https://user-images.githubusercontent.com/114439510/213503933-47560340-7957-4b44-98a5-1a70203cdcfa.png)

**Wakatime**
![imagen](https://user-images.githubusercontent.com/114439510/213504217-64f9146a-3324-401a-9f26-bce303f0c77e.png)

**Dashboard Wakatime** [URL](https://wakatime.com/dashboard?start=2023-01-13&end=2023-01-19)

**Brayan Enrique Pinzón Quiñonez.** 

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
83%
### Retroalimentación
Faltó el desarrollo de las funcionalidades de editar y eliminar inmueble.
