### ISSUE TITLE
Project Sprint3

### ISSUE THREAD

**Issue by Jaime-U-Lopez** [MAKAIABootcamp/fundamentos-back1#75]
# Project Sprint 3 

#### Imagen project:

![Screenshot from 2023-01-19 14-02-14](https://user-images.githubusercontent.com/50783391/213536185-fef516a6-d3b0-4194-9615-2337b6282ecc.png)
![Screenshot from 2023-01-19 14-02-08](https://user-images.githubusercontent.com/50783391/213536208-68a1a403-98e7-4728-95af-badf269e2179.png)
![Screenshot from 2023-01-19 14-02-49](https://user-images.githubusercontent.com/50783391/213536289-c7e4eb01-e134-4d9d-b34a-2318b11b9990.png)
![Screenshot from 2023-01-19 14-08-37](https://user-images.githubusercontent.com/50783391/213537483-3d0f287b-ea60-4abf-93b8-151a73eda878.png)

![Screenshot from 2023-01-19 14-03-31](https://user-images.githubusercontent.com/50783391/213536462-97ebe0a3-5efb-436e-99de-3d109a4b836a.png)

#### Imagen Wakatime:

![image](https://user-images.githubusercontent.com/50783391/213536915-015525f8-b037-4247-b4d9-a746a5202dd5.png)

![image](https://user-images.githubusercontent.com/50783391/213537112-6fd1c9f3-3c8d-4e72-8fff-46c1450d69c4.png)

Creator:  Jaime  Orlando urrego
For:

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
103%
### Retroalimentación
Muy buen trabajo!
