### ISSUE TITLE
Entrega Proyecto Sprint 3

### ISSUE THREAD

**Issue by afprietoa** [MAKAIABootcamp/fundamentos-back1#76]
# CasaRoyal

URL GitHub Repository: [CasaRoyal Repository](https://github.com/afprietoa/CasaRoyal)
URL GitHub Pages: [CasaRoyal Deployment](https://afprietoa.github.io/CasaRoyal/)

## Explicación técnica

Se desarrollo un sitio web de una compañia inmobiliaria en el cual se implemento un CRUD con javascript asíncronico simulando una API REST con json-server.

### Home Page
![screencapture-CasaRoyal](https://user-images.githubusercontent.com/68924563/213805725-4e042d9b-f961-4c36-8354-cfcf4012f2d6.png)

### Detail Page
![screencapture-CasaRoyal2](https://user-images.githubusercontent.com/68924563/213591039-b6b8bce6-0101-4c64-9a31-ac71295df391.png)

### Form Page
![screencapture-CasaRoyal3](https://user-images.githubusercontent.com/68924563/213609424-feb97a0a-3cce-411e-b64e-6d1f22a49a6f.png)

## Wakatime
![image](https://user-images.githubusercontent.com/68924563/213804765-da64066e-4b0d-4962-b5cf-2bc0a373f83b.png)

### Integrante
- Andrés Prieto

@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
103%
### Retroalimentación
Excelente proyecto!
