### ISSUE TITLE
Proyecto Sprint 3

### ISSUE THREAD

**Issue by Edward-Reyes-Vanegas** [MAKAIABootcamp/fundamentos-back1#77]
![Diapositiva1](https://user-images.githubusercontent.com/120218145/213829940-9f73ff36-df48-41b5-bd7f-1f9e6e8de12a.PNG)
![Diapositiva2](https://user-images.githubusercontent.com/120218145/213829942-dc6fa391-ffe0-428e-8fe2-d1bfaf7ac0a6.PNG)
![Diapositiva1](https://user-images.githubusercontent.com/120218145/213829955-fbf816ee-df46-46f4-a0af-d24cd431ae3d.PNG)
![Diapositiva2](https://user-images.githubusercontent.com/120218145/213829957-aa756cc8-6374-40cc-a5ca-1ac444f81a89.PNG)
![Wakatime](https://user-images.githubusercontent.com/120218145/213828320-65568be6-b444-48f8-85fc-99c5c6d78eef.PNG)
## Explicación del desarrollo técnico
Esta es una aplicacion para venta inmobiliaria aplicando html css y funcionalidad de una pagina local storage y sesion storage, concepto JSON-Server y Async Await 

@Edward-Reyes-Vanegas 
## Imagen de las vistas
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
74%
### Retroalimentación
1. ¿Porqué se usan dependencias como jquery? jquery es una librería de JavaScript que ya está deprecada y en desuso.
2. Se evidencia desarrollo de vistas (pages) como la de sign in que no fueron requeridas dentro de los entregables
3. No se evidencia uso de la estructura HTML Semántico
4. La interfaz de las diferentes vistas no cumplen con el diseño UI suministrado.
5. No se encuentra funcional la página de detalles de un inmueble y búsqueda de inmueble por ubicación.
6. Se encuentra funcionalidad de adicionar a página de favoritos de manera parcial.
7. Se combina el framework de boostrap con SASS como preprocesador CSS.
8. Se baja puntaje en la calificación por uso de un template (y código) de una página ya construida.
![image](https://user-images.githubusercontent.com/98284374/214430014-f1b6ac07-4ca4-467d-b3de-78516bb92830.png)
