### ISSUE TITLE
Proyecto Sprint 3

### ISSUE THREAD

**Issue by ghost** [MAKAIABootcamp/fundamentos-back1#78]
## Características del proyecto:
- Diseño responsive utilizando (Html5, Css3, JavaScript)
- EventosDom para filtrar botones (Input, Select)
- Modules de JavaScript(Import/Export)
- JSON-SERVER(Peticiones Fetch) y métodos (GET, POST, DELETE, PUT)

### HOMEPAGE
![Principal](https://user-images.githubusercontent.com/119947851/214183212-cddb2a57-fad8-4a70-995a-93b8b5fbbd42.png)

## INMUEBLES
![Inmuebles](https://user-images.githubusercontent.com/119947851/214134231-3a91803e-8ab7-4479-a908-40b1652d91ec.png)

## DETALLES DE INMUEBLES
![detalles](https://user-images.githubusercontent.com/119947851/214135495-f798d095-de37-4fbf-a12b-6f7711d63ba9.png)

## FAVORITOS
![favoritos](https://user-images.githubusercontent.com/119947851/214183390-ed93a55a-e563-40ad-804b-b5f132fb7d4d.png)

## PLUS(FORMULARIO)
![Formulario](https://user-images.githubusercontent.com/119947851/214135532-a20178bf-8c7f-4e00-b7e4-e940cf0f7586.png)

## WAKATIME:
![wakatime](https://user-images.githubusercontent.com/119947851/214136236-0879f41f-0c98-472c-aa73-2cfc3742005b.png)

## Presentado por:
Juan Camilo Restrepo B.

**Comment by WhitneySt** [comment]
### Calificación
74%
### Retroalimentación

1. Página de favoritos y búsqueda por ubicación no se encuentra funcional
