### ISSUE TITLE
proyecto Sprint 3 

### ISSUE THREAD

**Issue by sebastian1695** [MAKAIABootcamp/fundamentos-back1#79]
Sprint 3

#URL https://sprint3casaroyalex.netlify.app/
#URL repositorio https://github.com/sebastian1695/CasaRoyalEx

descripcion proyyecto

Página que simula el funcionamiento de una empresa de finca raíz. Se usa HTML, JS y CSS para el funcionamiento y estilo de la página. Esta puede crear nuevas propiedades, editarlas y borrarlas. Así como permite divisarlas. 

imagen proyecto

![ss casa royal](https://user-images.githubusercontent.com/119948037/214318386-43546be3-d757-4da7-b1a0-7e102be96e88.png)

imagen wakatime

![Screen Shot 2023-01-24 at 9 21 18 AM](https://user-images.githubusercontent.com/119948037/214319756-5fdab286-9a4f-4414-b958-b9c82931c84d.png)
![Screen Shot 2023-01-24 at 9 20 45 AM](https://user-images.githubusercontent.com/119948037/214319868-9ff1d9db-7d98-44ff-a18d-66777ed227b7.png)

de @sebastian1695

para @WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
61%
### Retroalimentación
La página de favoritos, filtros de por tipo, búsqueda por ubicación y página de detalle de inmueble no funcional.
