### ISSUE TITLE
Entrega workshop 1 sprint

### ISSUE THREAD

**Issue by EstebanCanoC** [MAKAIABootcamp/fundamentos-back1#8]
## URL del repositorio
https://github.com/EstebanCanoC/Workshop_1

##Deploy
GhPages
-> https://estebancanoc.github.io/Workshop_1/
Vercel
-> https://workshop-1.vercel.app/

## Explicación del desarrollo técnico

Maquetado de una página web estática utilizando HTML (Lenguaje de Marcas de Hipertexto) & CSS (Hojas de Estilo en Cascada).

NOTA: Se que el Mockup que se proporcionó se hizo como referencia para crear una página con cierta estructura. Decidí tratar de recrear la página lo más fidedigna posible (Segun he leído y he visto por ahi así es jajaja, ya que el departamento de diseño manda algo y la idea es hacerlo lo más parecida posible). 

-> Me gustó mucho el Mockup.

Entonces lo tome como reto personal.  Conservare esta como una primera version para hacer lo siguiente:
1. Crear un botón que me cambie la página de B/N a color.
2. Cuando se creen paginas dinámicas, utilizar recursividad para recrear el juego ¿Quién es ese Pokémon? Who's that Pokémon? Ya que me lo recordó apenas ver el Mockup.

De igual manera la página web cuenta con lo siguiente:
1. HTML semántico.
2. CSS y uso de Pseudoclases.
3. Responsive.

## Imagen de las vistas
![workshop-1 vercel app_(iPhone SE)](https://user-images.githubusercontent.com/72243661/207760456-f2ca3b7a-aeed-4032-b344-dcabd3df454c.jpg)
![DesktopView](https://user-images.githubusercontent.com/72243661/207760480-a9ed37b6-9a47-42b7-a968-983cbe518c3c.jpg)

## Estadísticas de Wakatime
![Wakatime_workshop_1](https://user-images.githubusercontent.com/72243661/207760640-6d2d6a34-d5b9-43fa-97f2-873b009d7552.jpg)

**Comment by EstebanCanoC** [comment]
## Pseint
https://drive.google.com/drive/folders/1z6dBtW-3E09wJEaLZ29V96DuAtaA86jR?usp=sharing

**Comment by WhitneySt** [comment]
# Tarea Algoritmo PSEInt
Calificación: 100%
# Tarea Pokedex
Calificación: 100%

Excelente trabajo!
