### ISSUE TITLE
Proyecto Sprint 3

### ISSUE THREAD

**Issue by dianaperezdv** [MAKAIABootcamp/fundamentos-back1#80]
[**Url del repositorio**](https://github.com/dianaperezdv/sprint3)

[**Url del despliegue**](https://dianaperezdv.github.io/sprint3/sprint/index.html)

**Explicación del desarrollo:**

- Se desarrolló una página web que permitiera revisar las propiedades que hacen parte de la empresa. 
- Incluye funciones de filtrado, búsqueda por ubicación, revisión de detalles, agregar propiedades, página de favoritos, entre otros.
- Se usó html, css y javascript.

**VISTAS**

![image](https://user-images.githubusercontent.com/47093819/214588542-facf4a00-e804-46d4-a7d0-eac3ae9b1f59.png)
![image](https://user-images.githubusercontent.com/47093819/214589482-f65faed2-72c0-42fe-8c6c-ac47036bcd09.png)

Por: Diana Camila Pérez del Valle
@WhitneySt

**Comment by WhitneySt** [comment]
### Calificación
58%
### Retroalimentación
1. No se observa desarrollo del código de la funcionalidad de búsqueda de inmueble por ubicación
2. Se observa desarrollo del código pero inconvenientes en el funcionamiento en las características de crear, eliminar y editar inmuebles y agregar inmuebles a favoritos.
3. La nota es basada en la revisión del código, los criterios evaluados en la sustentación no son tenidos en cuenta.
